import { DailyBoardType } from 'src/types/board.type';
export let unique = 1;
let commentNumber = 1;
export const DailyBoard: DailyBoardType[] = [
  {
    _id: String(unique),
    title: '첫번째 게시글임',
    tags: '#태그#분리하기#됐나',
    contents: '여기에 내용, 사진 같이 들어감',
    heart: 1,
    commentCount: commentNumber++,
    comments: [],
    owner: {
      _id: '123124',
      email: 'email.gmail.com',
      avatarUrl: '..',
      name: '게시글작성자',
      __v: unique,
    },
    createdAt: new Date(),
    __v: unique++,
  },
  {
    _id: String(unique),
    title: '우선 댓글수로 페이지네이션 잘되나 확인해보자',
    tags: '#태그#분리하기#됐나',
    contents: '여기에 내용, 사진 같이 들어감',
    heart: 1,
    commentCount: commentNumber++,
    comments: [],
    owner: {
      _id: '123124',
      email: 'email.gmail.com',
      avatarUrl: '..',
      name: '게시글작성자',
      __v: unique,
    },
    createdAt: new Date(),
    __v: unique++,
  },
  {
    _id: String(unique),
    title: '타이틀',
    tags: '#태그#분리하기#됐나',
    contents: '여기에 내용, 사진 같이 들어감',
    heart: 1,
    commentCount: commentNumber++,
    comments: [],
    owner: {
      _id: '123124',
      email: 'email.gmail.com',
      avatarUrl: '..',
      name: '게시글작성자',
      __v: unique,
    },
    createdAt: new Date(),
    __v: unique++,
  },
  {
    _id: String(unique),
    title: '타이틀',
    tags: '#태그#분리하기#됐나',
    contents: '여기에 내용, 사진 같이 들어감',
    heart: 1,
    commentCount: commentNumber++,
    comments: [],
    owner: {
      _id: '123124',
      email: 'email.gmail.com',
      avatarUrl: '..',
      name: '게시글작성자',
      __v: unique,
    },
    createdAt: new Date(),
    __v: unique++,
  },
  {
    _id: String(unique),
    title: '타이틀',
    tags: '#태그#분리하기#됐나',
    contents: '여기에 내용, 사진 같이 들어감',
    heart: 1,
    commentCount: commentNumber++,
    comments: [],
    owner: {
      _id: '123124',
      email: 'email.gmail.com',
      avatarUrl: '..',
      name: '게시글작성자',
      __v: unique,
    },
    createdAt: new Date(),
    __v: unique++,
  },
  {
    _id: String(unique),
    title: '타이틀',
    tags: '#태그#분리하기#됐나',
    contents: '여기에 내용, 사진 같이 들어감',
    heart: 1,
    commentCount: commentNumber++,
    comments: [],
    owner: {
      _id: '123124',
      email: 'email.gmail.com',
      avatarUrl: '..',
      name: '게시글작성자',
      __v: unique,
    },
    createdAt: new Date(),
    __v: unique++,
  },
  {
    _id: String(unique),
    title: '타이틀',
    tags: '#태그#분리하기#됐나',
    contents: '여기에 내용, 사진 같이 들어감',
    heart: 1,
    commentCount: commentNumber++,
    comments: [],
    owner: {
      _id: '123124',
      email: 'email.gmail.com',
      avatarUrl: '..',
      name: '게시글작성자',
      __v: unique,
    },
    createdAt: new Date(),
    __v: unique++,
  },
  {
    _id: String(unique),
    title: '타이틀',
    tags: '#태그#분리하기#됐나',
    contents: '여기에 내용, 사진 같이 들어감',
    heart: 1,
    commentCount: commentNumber++,
    comments: [],
    owner: {
      _id: '123124',
      email: 'email.gmail.com',
      avatarUrl: '..',
      name: '게시글작성자',
      __v: unique,
    },
    createdAt: new Date(),
    __v: unique++,
  },
  {
    _id: String(unique),
    title: '타이틀',
    tags: '#태그#분리하기#됐나',
    contents: '여기에 내용, 사진 같이 들어감',
    heart: 1,
    commentCount: commentNumber++,
    comments: [],
    owner: {
      _id: '123124',
      email: 'email.gmail.com',
      avatarUrl: '..',
      name: '게시글작성자',
      __v: unique,
    },
    createdAt: new Date(),
    __v: unique++,
  },
  {
    _id: String(unique),
    title: '타이틀',
    tags: '#태그#분리하기#됐나',
    contents: '여기에 내용, 사진 같이 들어감',
    heart: 1,
    commentCount: commentNumber++,
    comments: [],
    owner: {
      _id: '123124',
      email: 'email.gmail.com',
      avatarUrl: '..',
      name: '게시글작성자',
      __v: unique,
    },
    createdAt: new Date(),
    __v: unique++,
  },
  {
    _id: String(unique),
    title: '타이틀',
    tags: '#태그#분리하기#됐나',
    contents: '여기에 내용, 사진 같이 들어감',
    heart: 1,
    commentCount: commentNumber++,
    comments: [],
    owner: {
      _id: '123124',
      email: 'email.gmail.com',
      avatarUrl: '..',
      name: '게시글작성자',
      __v: unique,
    },
    createdAt: new Date(),
    __v: unique++,
  },
  {
    _id: String(unique),
    title: '타이틀',
    tags: '#태그#분리하기#됐나',
    contents: '여기에 내용, 사진 같이 들어감',
    heart: 1,
    commentCount: commentNumber++,
    comments: [],
    owner: {
      _id: '123124',
      email: 'email.gmail.com',
      avatarUrl: '..',
      name: '게시글작성자',
      __v: unique,
    },
    createdAt: new Date(),
    __v: unique++,
  },
  {
    _id: String(unique),
    title: '타이틀',
    tags: '#태그#분리하기#됐나',
    contents: '여기에 내용, 사진 같이 들어감',
    heart: 1,
    commentCount: commentNumber++,
    comments: [],
    owner: {
      _id: '123124',
      email: 'email.gmail.com',
      avatarUrl: '..',
      name: '게시글작성자',
      __v: unique,
    },
    createdAt: new Date(),
    __v: unique++,
  },
  {
    _id: String(unique),
    title: '타이틀',
    tags: '#태그#분리하기#됐나',
    contents: '여기에 내용, 사진 같이 들어감',
    heart: 1,
    commentCount: commentNumber++,
    comments: [],
    owner: {
      _id: '123124',
      email: 'email.gmail.com',
      avatarUrl: '..',
      name: '게시글작성자',
      __v: unique,
    },
    createdAt: new Date(),
    __v: unique++,
  },
  {
    _id: String(unique),
    title: '타이틀',
    tags: '#태그#분리하기#됐나',
    contents: '여기에 내용, 사진 같이 들어감',
    heart: 1,
    commentCount: commentNumber++,
    comments: [],
    owner: {
      _id: '123124',
      email: 'email.gmail.com',
      avatarUrl: '..',
      name: '게시글작성자',
      __v: unique,
    },
    createdAt: new Date(),
    __v: unique++,
  },
  {
    _id: String(unique),
    title: '타이틀',
    tags: '#태그#분리하기#됐나',
    contents: '여기에 내용, 사진 같이 들어감',
    heart: 1,
    commentCount: commentNumber++,
    comments: [],
    owner: {
      _id: '123124',
      email: 'email.gmail.com',
      avatarUrl: '..',
      name: '게시글작성자',
      __v: unique,
    },
    createdAt: new Date(),
    __v: unique++,
  },
  {
    _id: String(unique),
    title: '타이틀',
    tags: '#태그#분리하기#됐나',
    contents: '여기에 내용, 사진 같이 들어감',
    heart: 1,
    commentCount: commentNumber++,
    comments: [],
    owner: {
      _id: '123124',
      email: 'email.gmail.com',
      avatarUrl: '..',
      name: '게시글작성자',
      __v: unique,
    },
    createdAt: new Date(),
    __v: unique++,
  },
  {
    _id: String(unique),
    title: '타이틀',
    tags: '#태그#분리하기#됐나',
    contents: '여기에 내용, 사진 같이 들어감',
    heart: 1,
    commentCount: commentNumber++,
    comments: [],
    owner: {
      _id: '123124',
      email: 'email.gmail.com',
      avatarUrl: '..',
      name: '게시글작성자',
      __v: unique,
    },
    createdAt: new Date(),
    __v: unique++,
  },
  {
    _id: String(unique),
    title: '타이틀',
    tags: '#태그#분리하기#됐나',
    contents: '여기에 내용, 사진 같이 들어감',
    heart: 1,
    commentCount: commentNumber++,
    comments: [],
    owner: {
      _id: '123124',
      email: 'email.gmail.com',
      avatarUrl: '..',
      name: '게시글작성자',
      __v: unique,
    },
    createdAt: new Date(),
    __v: unique++,
  },
  {
    _id: String(unique),
    title: '타이틀',
    tags: '#태그#분리하기#됐나',
    contents: '여기에 내용, 사진 같이 들어감',
    heart: 1,
    commentCount: commentNumber++,
    comments: [],
    owner: {
      _id: '123124',
      email: 'email.gmail.com',
      avatarUrl: '..',
      name: '게시글작성자',
      __v: unique,
    },
    createdAt: new Date(),
    __v: unique++,
  },
  {
    _id: String(unique),
    title: '타이틀',
    tags: '#태그#분리하기#됐나',
    contents: '여기에 내용, 사진 같이 들어감',
    heart: 1,
    commentCount: commentNumber++,
    comments: [],
    owner: {
      _id: '123124',
      email: 'email.gmail.com',
      avatarUrl: '..',
      name: '게시글작성자',
      __v: unique,
    },
    createdAt: new Date(),
    __v: unique++,
  },
  {
    _id: String(unique),
    title: '타이틀',
    tags: '#태그#분리하기#됐나',
    contents: '여기에 내용, 사진 같이 들어감',
    heart: 1,
    commentCount: commentNumber++,
    comments: [],
    owner: {
      _id: '123124',
      email: 'email.gmail.com',
      avatarUrl: '..',
      name: '게시글작성자',
      __v: unique,
    },
    createdAt: new Date(),
    __v: unique++,
  },
  {
    _id: String(unique),
    title: '타이틀',
    tags: '#태그#분리하기#됐나',
    contents: '여기에 내용, 사진 같이 들어감',
    heart: 1,
    commentCount: commentNumber++,
    comments: [],
    owner: {
      _id: '123124',
      email: 'email.gmail.com',
      avatarUrl: '..',
      name: '게시글작성자',
      __v: unique,
    },
    createdAt: new Date(),
    __v: unique++,
  },
  {
    _id: String(unique),
    title: '타이틀',
    tags: '#태그#분리하기#됐나',
    contents: '여기에 내용, 사진 같이 들어감',
    heart: 1,
    commentCount: commentNumber++,
    comments: [],
    owner: {
      _id: '123124',
      email: 'email.gmail.com',
      avatarUrl: '..',
      name: '게시글작성자',
      __v: unique,
    },
    createdAt: new Date(),
    __v: unique++,
  },
  {
    _id: String(unique),
    title: '타이틀',
    tags: '#태그#분리하기#됐나',
    contents: '여기에 내용, 사진 같이 들어감',
    heart: 1,
    commentCount: commentNumber++,
    comments: [],
    owner: {
      _id: '123124',
      email: 'email.gmail.com',
      avatarUrl: '..',
      name: '게시글작성자',
      __v: unique,
    },
    createdAt: new Date(),
    __v: unique++,
  },
  {
    _id: String(unique),
    title: '타이틀',
    tags: '#태그#분리하기#됐나',
    contents: '여기에 내용, 사진 같이 들어감',
    heart: 1,
    commentCount: commentNumber++,
    comments: [],
    owner: {
      _id: '123124',
      email: 'email.gmail.com',
      avatarUrl: '..',
      name: '게시글작성자',
      __v: unique,
    },
    createdAt: new Date(),
    __v: unique++,
  },
  {
    _id: String(unique),
    title: '타이틀',
    tags: '#태그#분리하기#됐나',
    contents: '여기에 내용, 사진 같이 들어감',
    heart: 1,
    commentCount: commentNumber++,
    comments: [],
    owner: {
      _id: '123124',
      email: 'email.gmail.com',
      avatarUrl: '..',
      name: '게시글작성자',
      __v: unique,
    },
    createdAt: new Date(),
    __v: unique++,
  },
  {
    _id: String(unique),
    title: '타이틀',
    tags: '#태그#분리하기#됐나',
    contents: '여기에 내용, 사진 같이 들어감',
    heart: 1,
    commentCount: commentNumber++,
    comments: [],
    owner: {
      _id: '123124',
      email: 'email.gmail.com',
      avatarUrl: '..',
      name: '게시글작성자',
      __v: unique,
    },
    createdAt: new Date(),
    __v: unique++,
  },
  {
    _id: String(unique),
    title: '타이틀',
    tags: '#태그#분리하기#됐나',
    contents: '여기에 내용, 사진 같이 들어감',
    heart: 1,
    commentCount: commentNumber++,
    comments: [],
    owner: {
      _id: '123124',
      email: 'email.gmail.com',
      avatarUrl: '..',
      name: '게시글작성자',
      __v: unique,
    },
    createdAt: new Date(),
    __v: unique++,
  },
  {
    _id: String(unique),
    title: '타이틀',
    tags: '#태그#분리하기#됐나',
    contents: '여기에 내용, 사진 같이 들어감',
    heart: 1,
    commentCount: commentNumber++,
    comments: [],
    owner: {
      _id: '123124',
      email: 'email.gmail.com',
      avatarUrl: '..',
      name: '게시글작성자',
      __v: unique,
    },
    createdAt: new Date(),
    __v: unique++,
  },
  {
    _id: String(unique),
    title: '타이틀',
    tags: '#태그#분리하기#됐나',
    contents: '여기에 내용, 사진 같이 들어감',
    heart: 1,
    commentCount: commentNumber++,
    comments: [],
    owner: {
      _id: '123124',
      email: 'email.gmail.com',
      avatarUrl: '..',
      name: '게시글작성자',
      __v: unique,
    },
    createdAt: new Date(),
    __v: unique++,
  },
  {
    _id: String(unique),
    title: '타이틀',
    tags: '#태그#분리하기#됐나',
    contents: '여기에 내용, 사진 같이 들어감',
    heart: 1,
    commentCount: commentNumber++,
    comments: [],
    owner: {
      _id: '123124',
      email: 'email.gmail.com',
      avatarUrl: '..',
      name: '게시글작성자',
      __v: unique,
    },
    createdAt: new Date(),
    __v: unique++,
  },
  {
    _id: String(unique),
    title: '타이틀',
    tags: '#태그#분리하기#됐나',
    contents: '여기에 내용, 사진 같이 들어감',
    heart: 1,
    commentCount: commentNumber++,
    comments: [],
    owner: {
      _id: '123124',
      email: 'email.gmail.com',
      avatarUrl: '..',
      name: '게시글작성자',
      __v: unique,
    },
    createdAt: new Date(),
    __v: unique++,
  },
  {
    _id: String(unique),
    title: '타이틀',
    tags: '#태그#분리하기#됐나',
    contents: '여기에 내용, 사진 같이 들어감',
    heart: 1,
    commentCount: commentNumber++,
    comments: [],
    owner: {
      _id: '123124',
      email: 'email.gmail.com',
      avatarUrl: '..',
      name: '게시글작성자',
      __v: unique,
    },
    createdAt: new Date(),
    __v: unique++,
  },
  {
    _id: String(unique),
    title: '타이틀',
    tags: '#태그#분리하기#됐나',
    contents: '여기에 내용, 사진 같이 들어감',
    heart: 1,
    commentCount: commentNumber++,
    comments: [],
    owner: {
      _id: '123124',
      email: 'email.gmail.com',
      avatarUrl: '..',
      name: '게시글작성자',
      __v: unique,
    },
    createdAt: new Date(),
    __v: unique++,
  },
  {
    _id: String(unique),
    title: '타이틀',
    tags: '#태그#분리하기#됐나',
    contents: '여기에 내용, 사진 같이 들어감',
    heart: 1,
    commentCount: commentNumber++,
    comments: [],
    owner: {
      _id: '123124',
      email: 'email.gmail.com',
      avatarUrl: '..',
      name: '게시글작성자',
      __v: unique,
    },
    createdAt: new Date(),
    __v: unique++,
  },
  {
    _id: String(unique),
    title: '타이틀',
    tags: '#태그#분리하기#됐나',
    contents: '여기에 내용, 사진 같이 들어감',
    heart: 1,
    commentCount: commentNumber++,
    comments: [],
    owner: {
      _id: '123124',
      email: 'email.gmail.com',
      avatarUrl: '..',
      name: '게시글작성자',
      __v: unique,
    },
    createdAt: new Date(),
    __v: unique++,
  },
  {
    _id: String(unique),
    title: '타이틀',
    tags: '#태그#분리하기#됐나',
    contents: '여기에 내용, 사진 같이 들어감',
    heart: 1,
    commentCount: commentNumber++,
    comments: [],
    owner: {
      _id: '123124',
      email: 'email.gmail.com',
      avatarUrl: '..',
      name: '게시글작성자',
      __v: unique,
    },
    createdAt: new Date(),
    __v: unique++,
  },
  {
    _id: String(unique),
    title: '타이틀',
    tags: '#태그#분리하기#됐나',
    contents: '여기에 내용, 사진 같이 들어감',
    heart: 1,
    commentCount: commentNumber++,
    comments: [],
    owner: {
      _id: '123124',
      email: 'email.gmail.com',
      avatarUrl: '..',
      name: '게시글작성자',
      __v: unique,
    },
    createdAt: new Date(),
    __v: unique++,
  },
  {
    _id: String(unique),
    title: '타이틀',
    tags: '#태그#분리하기#됐나',
    contents: '여기에 내용, 사진 같이 들어감',
    heart: 1,
    commentCount: commentNumber++,
    comments: [],
    owner: {
      _id: '123124',
      email: 'email.gmail.com',
      avatarUrl: '..',
      name: '게시글작성자',
      __v: unique,
    },
    createdAt: new Date(),
    __v: unique++,
  },
  {
    _id: String(unique),
    title: '타이틀',
    tags: '#태그#분리하기#됐나',
    contents: '여기에 내용, 사진 같이 들어감',
    heart: 1,
    commentCount: commentNumber++,
    comments: [],
    owner: {
      _id: '123124',
      email: 'email.gmail.com',
      avatarUrl: '..',
      name: '게시글작성자',
      __v: unique,
    },
    createdAt: new Date(),
    __v: unique++,
  },
];
