import { DailyBoardType } from 'src/types/board.type';

let unique = 1;
export const DailyBoard: DailyBoardType[] = [
  {
    _id: String(unique),
    title: '타이틀',
    tags: '#태그#나중에#분리하기',
    contents: '여기에 내용, 사진 같이 들어감',
    heart: 1,
    commentCount: 1,
    comments: [],
    owner: {
      _id: '123124',
      email: 'email.gmail.com',
      avatarUrl: '..',
      name: '게시글작성자',
      __v: unique,
    },
    createdAt: new Date(),
    __v: unique++,
  },
  {
    _id: String(unique),
    title: '타이틀',
    tags: '#태그#나중에#분리하기',
    contents: '여기에 내용, 사진 같이 들어감',
    heart: 1,
    commentCount: 1,
    comments: [],
    owner: {
      _id: '123124',
      email: 'email.gmail.com',
      avatarUrl: '..',
      name: '게시글작성자',
      __v: unique,
    },
    createdAt: new Date(),
    __v: unique++,
  },
  {
    _id: String(unique),
    title: '타이틀',
    tags: '#태그#나중에#분리하기',
    contents: '여기에 내용, 사진 같이 들어감',
    heart: 1,
    commentCount: 1,
    comments: [],
    owner: {
      _id: '123124',
      email: 'email.gmail.com',
      avatarUrl: '..',
      name: '게시글작성자',
      __v: unique,
    },
    createdAt: new Date(),
    __v: unique++,
  },
  {
    _id: String(unique),
    title: '타이틀',
    tags: '#태그#나중에#분리하기',
    contents: '여기에 내용, 사진 같이 들어감',
    heart: 1,
    commentCount: 1,
    comments: [],
    owner: {
      _id: '123124',
      email: 'email.gmail.com',
      avatarUrl: '..',
      name: '게시글작성자',
      __v: unique,
    },
    createdAt: new Date(),
    __v: unique++,
  },
  {
    _id: String(unique),
    title: '타이틀',
    tags: '#태그#나중에#분리하기',
    contents: '여기에 내용, 사진 같이 들어감',
    heart: 1,
    commentCount: 1,
    comments: [],
    owner: {
      _id: '123124',
      email: 'email.gmail.com',
      avatarUrl: '..',
      name: '게시글작성자',
      __v: unique,
    },
    createdAt: new Date(),
    __v: unique++,
  },
  {
    _id: String(unique),
    title: '타이틀',
    tags: '#태그#나중에#분리하기',
    contents: '여기에 내용, 사진 같이 들어감',
    heart: 1,
    commentCount: 1,
    comments: [],
    owner: {
      _id: '123124',
      email: 'email.gmail.com',
      avatarUrl: '..',
      name: '게시글작성자',
      __v: unique,
    },
    createdAt: new Date(),
    __v: unique++,
  },
  {
    _id: String(unique),
    title: '타이틀',
    tags: '#태그#나중에#분리하기',
    contents: '여기에 내용, 사진 같이 들어감',
    heart: 1,
    commentCount: 1,
    comments: [],
    owner: {
      _id: '123124',
      email: 'email.gmail.com',
      avatarUrl: '..',
      name: '게시글작성자',
      __v: unique,
    },
    createdAt: new Date(),
    __v: unique++,
  },
  {
    _id: String(unique),
    title: '타이틀',
    tags: '#태그#나중에#분리하기',
    contents: '여기에 내용, 사진 같이 들어감',
    heart: 1,
    commentCount: 1,
    comments: [],
    owner: {
      _id: '123124',
      email: 'email.gmail.com',
      avatarUrl: '..',
      name: '게시글작성자',
      __v: unique,
    },
    createdAt: new Date(),
    __v: unique++,
  },
  {
    _id: String(unique),
    title: '타이틀',
    tags: '#태그#나중에#분리하기',
    contents: '여기에 내용, 사진 같이 들어감',
    heart: 1,
    commentCount: 1,
    comments: [],
    owner: {
      _id: '123124',
      email: 'email.gmail.com',
      avatarUrl: '..',
      name: '게시글작성자',
      __v: unique,
    },
    createdAt: new Date(),
    __v: unique++,
  },
  {
    _id: String(unique),
    title: '타이틀',
    tags: '#태그#나중에#분리하기',
    contents: '여기에 내용, 사진 같이 들어감',
    heart: 1,
    commentCount: 1,
    comments: [],
    owner: {
      _id: '123124',
      email: 'email.gmail.com',
      avatarUrl: '..',
      name: '게시글작성자',
      __v: unique,
    },
    createdAt: new Date(),
    __v: unique++,
  },
  {
    _id: String(unique),
    title: '타이틀',
    tags: '#태그#나중에#분리하기',
    contents: '여기에 내용, 사진 같이 들어감',
    heart: 1,
    commentCount: 1,
    comments: [],
    owner: {
      _id: '123124',
      email: 'email.gmail.com',
      avatarUrl: '..',
      name: '게시글작성자',
      __v: unique,
    },
    createdAt: new Date(),
    __v: unique++,
  },
  {
    _id: String(unique),
    title: '타이틀',
    tags: '#태그#나중에#분리하기',
    contents: '여기에 내용, 사진 같이 들어감',
    heart: 1,
    commentCount: 1,
    comments: [],
    owner: {
      _id: '123124',
      email: 'email.gmail.com',
      avatarUrl: '..',
      name: '게시글작성자',
      __v: unique,
    },
    createdAt: new Date(),
    __v: unique++,
  },
  {
    _id: String(unique),
    title: '타이틀',
    tags: '#태그#나중에#분리하기',
    contents: '여기에 내용, 사진 같이 들어감',
    heart: 1,
    commentCount: 1,
    comments: [],
    owner: {
      _id: '123124',
      email: 'email.gmail.com',
      avatarUrl: '..',
      name: '게시글작성자',
      __v: unique,
    },
    createdAt: new Date(),
    __v: unique++,
  },
  {
    _id: String(unique),
    title: '타이틀',
    tags: '#태그#나중에#분리하기',
    contents: '여기에 내용, 사진 같이 들어감',
    heart: 1,
    commentCount: 1,
    comments: [],
    owner: {
      _id: '123124',
      email: 'email.gmail.com',
      avatarUrl: '..',
      name: '게시글작성자',
      __v: unique,
    },
    createdAt: new Date(),
    __v: unique++,
  },
  {
    _id: String(unique),
    title: '타이틀',
    tags: '#태그#나중에#분리하기',
    contents: '여기에 내용, 사진 같이 들어감',
    heart: 1,
    commentCount: 1,
    comments: [],
    owner: {
      _id: '123124',
      email: 'email.gmail.com',
      avatarUrl: '..',
      name: '게시글작성자',
      __v: unique,
    },
    createdAt: new Date(),
    __v: unique++,
  },
  {
    _id: String(unique),
    title: '타이틀',
    tags: '#태그#나중에#분리하기',
    contents: '여기에 내용, 사진 같이 들어감',
    heart: 1,
    commentCount: 1,
    comments: [],
    owner: {
      _id: '123124',
      email: 'email.gmail.com',
      avatarUrl: '..',
      name: '게시글작성자',
      __v: unique,
    },
    createdAt: new Date(),
    __v: unique++,
  },
  {
    _id: String(unique),
    title: '타이틀',
    tags: '#태그#나중에#분리하기',
    contents: '여기에 내용, 사진 같이 들어감',
    heart: 1,
    commentCount: 1,
    comments: [],
    owner: {
      _id: '123124',
      email: 'email.gmail.com',
      avatarUrl: '..',
      name: '게시글작성자',
      __v: unique,
    },
    createdAt: new Date(),
    __v: unique++,
  },
  {
    _id: String(unique),
    title: '타이틀',
    tags: '#태그#나중에#분리하기',
    contents: '여기에 내용, 사진 같이 들어감',
    heart: 1,
    commentCount: 1,
    comments: [],
    owner: {
      _id: '123124',
      email: 'email.gmail.com',
      avatarUrl: '..',
      name: '게시글작성자',
      __v: unique,
    },
    createdAt: new Date(),
    __v: unique++,
  },
  {
    _id: String(unique),
    title: '타이틀',
    tags: '#태그#나중에#분리하기',
    contents: '여기에 내용, 사진 같이 들어감',
    heart: 1,
    commentCount: 1,
    comments: [],
    owner: {
      _id: '123124',
      email: 'email.gmail.com',
      avatarUrl: '..',
      name: '게시글작성자',
      __v: unique,
    },
    createdAt: new Date(),
    __v: unique++,
  },
  {
    _id: String(unique),
    title: '타이틀',
    tags: '#태그#나중에#분리하기',
    contents: '여기에 내용, 사진 같이 들어감',
    heart: 1,
    commentCount: 1,
    comments: [],
    owner: {
      _id: '123124',
      email: 'email.gmail.com',
      avatarUrl: '..',
      name: '게시글작성자',
      __v: unique,
    },
    createdAt: new Date(),
    __v: unique++,
  },
  {
    _id: String(unique),
    title: '타이틀',
    tags: '#태그#나중에#분리하기',
    contents: '여기에 내용, 사진 같이 들어감',
    heart: 1,
    commentCount: 1,
    comments: [],
    owner: {
      _id: '123124',
      email: 'email.gmail.com',
      avatarUrl: '..',
      name: '게시글작성자',
      __v: unique,
    },
    createdAt: new Date(),
    __v: unique++,
  },
  {
    _id: String(unique),
    title: '타이틀',
    tags: '#태그#나중에#분리하기',
    contents: '여기에 내용, 사진 같이 들어감',
    heart: 1,
    commentCount: 1,
    comments: [],
    owner: {
      _id: '123124',
      email: 'email.gmail.com',
      avatarUrl: '..',
      name: '게시글작성자',
      __v: unique,
    },
    createdAt: new Date(),
    __v: unique++,
  },
  {
    _id: String(unique),
    title: '타이틀',
    tags: '#태그#나중에#분리하기',
    contents: '여기에 내용, 사진 같이 들어감',
    heart: 1,
    commentCount: 1,
    comments: [],
    owner: {
      _id: '123124',
      email: 'email.gmail.com',
      avatarUrl: '..',
      name: '게시글작성자',
      __v: unique,
    },
    createdAt: new Date(),
    __v: unique++,
  },
  {
    _id: String(unique),
    title: '타이틀',
    tags: '#태그#나중에#분리하기',
    contents: '여기에 내용, 사진 같이 들어감',
    heart: 1,
    commentCount: 1,
    comments: [],
    owner: {
      _id: '123124',
      email: 'email.gmail.com',
      avatarUrl: '..',
      name: '게시글작성자',
      __v: unique,
    },
    createdAt: new Date(),
    __v: unique++,
  },
  {
    _id: String(unique),
    title: '타이틀',
    tags: '#태그#나중에#분리하기',
    contents: '여기에 내용, 사진 같이 들어감',
    heart: 1,
    commentCount: 1,
    comments: [],
    owner: {
      _id: '123124',
      email: 'email.gmail.com',
      avatarUrl: '..',
      name: '게시글작성자',
      __v: unique,
    },
    createdAt: new Date(),
    __v: unique++,
  },
  {
    _id: String(unique),
    title: '타이틀',
    tags: '#태그#나중에#분리하기',
    contents: '여기에 내용, 사진 같이 들어감',
    heart: 1,
    commentCount: 1,
    comments: [],
    owner: {
      _id: '123124',
      email: 'email.gmail.com',
      avatarUrl: '..',
      name: '게시글작성자',
      __v: unique,
    },
    createdAt: new Date(),
    __v: unique++,
  },
  {
    _id: String(unique),
    title: '타이틀',
    tags: '#태그#나중에#분리하기',
    contents: '여기에 내용, 사진 같이 들어감',
    heart: 1,
    commentCount: 1,
    comments: [],
    owner: {
      _id: '123124',
      email: 'email.gmail.com',
      avatarUrl: '..',
      name: '게시글작성자',
      __v: unique,
    },
    createdAt: new Date(),
    __v: unique++,
  },
  {
    _id: String(unique),
    title: '타이틀',
    tags: '#태그#나중에#분리하기',
    contents: '여기에 내용, 사진 같이 들어감',
    heart: 1,
    commentCount: 1,
    comments: [],
    owner: {
      _id: '123124',
      email: 'email.gmail.com',
      avatarUrl: '..',
      name: '게시글작성자',
      __v: unique,
    },
    createdAt: new Date(),
    __v: unique++,
  },
  {
    _id: String(unique),
    title: '타이틀',
    tags: '#태그#나중에#분리하기',
    contents: '여기에 내용, 사진 같이 들어감',
    heart: 1,
    commentCount: 1,
    comments: [],
    owner: {
      _id: '123124',
      email: 'email.gmail.com',
      avatarUrl: '..',
      name: '게시글작성자',
      __v: unique,
    },
    createdAt: new Date(),
    __v: unique++,
  },
  {
    _id: String(unique),
    title: '타이틀',
    tags: '#태그#나중에#분리하기',
    contents: '여기에 내용, 사진 같이 들어감',
    heart: 1,
    commentCount: 1,
    comments: [],
    owner: {
      _id: '123124',
      email: 'email.gmail.com',
      avatarUrl: '..',
      name: '게시글작성자',
      __v: unique,
    },
    createdAt: new Date(),
    __v: unique++,
  },
  {
    _id: String(unique),
    title: '타이틀',
    tags: '#태그#나중에#분리하기',
    contents: '여기에 내용, 사진 같이 들어감',
    heart: 1,
    commentCount: 1,
    comments: [],
    owner: {
      _id: '123124',
      email: 'email.gmail.com',
      avatarUrl: '..',
      name: '게시글작성자',
      __v: unique,
    },
    createdAt: new Date(),
    __v: unique++,
  },
  {
    _id: String(unique),
    title: '타이틀',
    tags: '#태그#나중에#분리하기',
    contents: '여기에 내용, 사진 같이 들어감',
    heart: 1,
    commentCount: 1,
    comments: [],
    owner: {
      _id: '123124',
      email: 'email.gmail.com',
      avatarUrl: '..',
      name: '게시글작성자',
      __v: unique,
    },
    createdAt: new Date(),
    __v: unique++,
  },
  {
    _id: String(unique),
    title: '타이틀',
    tags: '#태그#나중에#분리하기',
    contents: '여기에 내용, 사진 같이 들어감',
    heart: 1,
    commentCount: 1,
    comments: [],
    owner: {
      _id: '123124',
      email: 'email.gmail.com',
      avatarUrl: '..',
      name: '게시글작성자',
      __v: unique,
    },
    createdAt: new Date(),
    __v: unique++,
  },
  {
    _id: String(unique),
    title: '타이틀',
    tags: '#태그#나중에#분리하기',
    contents: '여기에 내용, 사진 같이 들어감',
    heart: 1,
    commentCount: 1,
    comments: [],
    owner: {
      _id: '123124',
      email: 'email.gmail.com',
      avatarUrl: '..',
      name: '게시글작성자',
      __v: unique,
    },
    createdAt: new Date(),
    __v: unique++,
  },
  {
    _id: String(unique),
    title: '타이틀',
    tags: '#태그#나중에#분리하기',
    contents: '여기에 내용, 사진 같이 들어감',
    heart: 1,
    commentCount: 1,
    comments: [],
    owner: {
      _id: '123124',
      email: 'email.gmail.com',
      avatarUrl: '..',
      name: '게시글작성자',
      __v: unique,
    },
    createdAt: new Date(),
    __v: unique++,
  },
  {
    _id: String(unique),
    title: '타이틀',
    tags: '#태그#나중에#분리하기',
    contents: '여기에 내용, 사진 같이 들어감',
    heart: 1,
    commentCount: 1,
    comments: [],
    owner: {
      _id: '123124',
      email: 'email.gmail.com',
      avatarUrl: '..',
      name: '게시글작성자',
      __v: unique,
    },
    createdAt: new Date(),
    __v: unique++,
  },
  {
    _id: String(unique),
    title: '타이틀',
    tags: '#태그#나중에#분리하기',
    contents: '여기에 내용, 사진 같이 들어감',
    heart: 1,
    commentCount: 1,
    comments: [],
    owner: {
      _id: '123124',
      email: 'email.gmail.com',
      avatarUrl: '..',
      name: '게시글작성자',
      __v: unique,
    },
    createdAt: new Date(),
    __v: unique++,
  },
  {
    _id: String(unique),
    title: '타이틀',
    tags: '#태그#나중에#분리하기',
    contents: '여기에 내용, 사진 같이 들어감',
    heart: 1,
    commentCount: 1,
    comments: [],
    owner: {
      _id: '123124',
      email: 'email.gmail.com',
      avatarUrl: '..',
      name: '게시글작성자',
      __v: unique,
    },
    createdAt: new Date(),
    __v: unique++,
  },
  {
    _id: String(unique),
    title: '타이틀',
    tags: '#태그#나중에#분리하기',
    contents: '여기에 내용, 사진 같이 들어감',
    heart: 1,
    commentCount: 1,
    comments: [],
    owner: {
      _id: '123124',
      email: 'email.gmail.com',
      avatarUrl: '..',
      name: '게시글작성자',
      __v: unique,
    },
    createdAt: new Date(),
    __v: unique++,
  },
  {
    _id: String(unique),
    title: '타이틀',
    tags: '#태그#나중에#분리하기',
    contents: '여기에 내용, 사진 같이 들어감',
    heart: 1,
    commentCount: 1,
    comments: [],
    owner: {
      _id: '123124',
      email: 'email.gmail.com',
      avatarUrl: '..',
      name: '게시글작성자',
      __v: unique,
    },
    createdAt: new Date(),
    __v: unique++,
  },
  {
    _id: String(unique),
    title: '타이틀',
    tags: '#태그#나중에#분리하기',
    contents: '여기에 내용, 사진 같이 들어감',
    heart: 1,
    commentCount: 1,
    comments: [],
    owner: {
      _id: '123124',
      email: 'email.gmail.com',
      avatarUrl: '..',
      name: '게시글작성자',
      __v: unique,
    },
    createdAt: new Date(),
    __v: unique++,
  },
];
