import { InformationBoardType } from 'src/types/board.type';

let unique = 1;
export const InformationBoardData: InformationBoardType[] = [
  {
    _id: String(unique),
    title: '너무 재미있는 여행이였어요',
    category: '여행',
    city: '대구',
    detailCity: '북구',
    tags: '#여행#대구#북구',
    contents:
      '![imageURL](https://meongmeong-tui-img-storage.s3-ap-northeast-2.amazonaws.com/dcb35e89-1ffe-43c3-a5c6-a00b7d9a84f2.jpeg)대구에 여행을 갔다왔습니다. 카운터에 문의 후 반려동물을 데려갔는데 데려가서 케어해주시더라구요! 너무 좋았습니다',
    heart: 1,
    commentCount: 1,
    comments: [],
    owner: {
      _id: '123124',
      email: 'email.gmail.com',
      avatarUrl: '..',
      name: '주인또는집사',
      __v: unique,
    },
    createdAt: new Date(2022, 2, 20, 2, 3),
    __v: unique++,
  },
  {
    _id: String(unique),
    title: '타이틀',
    category: '음식점',
    city: '서울',
    detailCity: '홍대',
    tags: '#맛집#대박#서울#홍대',
    contents:
      '![imageURL](https://meongmeong-tui-img-storage.s3-ap-northeast-2.amazonaws.com/dcb35e89-1ffe-43c3-a5c6-a00b7d9a84f2.jpeg)진짜 맛있는 맛집이 있는데 소개해드릴려고 합니다! 반려동물도 같이 들어갈수있대요! 너무 좋았습니다',
    heart: 1,
    commentCount: 1,
    comments: [],
    owner: {
      _id: '123124',
      email: 'email.gmail.com',
      avatarUrl: '..',
      name: '고재민',
      __v: unique,
    },
    createdAt: new Date(2022, 2, 20, 2, 3),
    __v: unique++,
  },
  {
    _id: String(unique),
    title: '타이틀',
    category: '숙소',
    city: '경기',
    detailCity: '군포',
    tags: '#숙소#행복#경기#군포',
    contents:
      '![imageURL](https://meongmeong-tui-img-storage.s3-ap-northeast-2.amazonaws.com/dcb35e89-1ffe-43c3-a5c6-a00b7d9a84f2.jpeg)숙소를 알아봤는데, 반려동물도 출입이 가능한곳이 있더라구요! 정말 잘됐습니다 저는 반려동물과 함께 행복한 시간을 보냈답니다!',
    heart: 1,
    commentCount: 1,
    comments: [],
    owner: {
      _id: '123124',
      email: 'email.gmail.com',
      avatarUrl: '..',
      name: '윤운일',
      __v: unique,
    },
    createdAt: new Date(2022, 2, 20, 2, 3),
    __v: unique++,
  },
  {
    _id: String(unique),
    title: '타이틀',
    category: '기타',
    city: '서울',
    detailCity: '마포동',
    tags: '#산책#공원#운동',
    contents:
      '![imageURL](https://meongmeong-tui-img-storage.s3-ap-northeast-2.amazonaws.com/8a38540c-fc7c-461c-96b7-268dc9c6d29e.jpeg)서울 마포동에 위치한 산책로인데, 다른사람들과 공유하고 싶어서 글을 올립니다 여기 되게 좋아요!',
    heart: 1,
    commentCount: 1,
    comments: [],
    owner: {
      _id: '123124',
      email: 'email.gmail.com',
      avatarUrl: '..',
      name: '박상훈',
      __v: unique,
    },
    createdAt: new Date(2022, 2, 20, 2, 2),
    __v: unique++,
  },
  {
    _id: String(unique),
    title: '진짜 행복한 추억을 남겼네요',
    category: '여행',
    city: '부산',
    detailCity: '해운대',
    tags: '#여행#부산#바다#추억',
    contents:
      '![imageURL](https://meongmeong-tui-img-storage.s3-ap-northeast-2.amazonaws.com/8a38540c-fc7c-461c-96b7-268dc9c6d29e.jpeg)강아지들과 바다보러 해운대에 갔는데 강아지들이 너무 행복해했고 저도 그 모습을 보면서 너무 행복했습니다~',
    heart: 1,
    commentCount: 1,
    comments: [],
    owner: {
      _id: '123124',
      email: 'email.gmail.com',
      avatarUrl: '..',
      name: '서은영',
      __v: unique,
    },
    createdAt: new Date(2022, 3, 23, 18, 22),
    __v: unique++,
  },
  {
    _id: String(unique),
    title: '타이틀',
    category: '음식점',
    city: '인천',
    detailCity: '구월동',
    tags: '#맛집#튀김#편안',
    contents:
      '![imageURL](https://meongmeong-tui-img-storage.s3-ap-northeast-2.amazonaws.com/8a38540c-fc7c-461c-96b7-268dc9c6d29e.jpeg)인천 구월동에 있는 튀김 전문점에 갔다왔는데 강아지 출입을 허용하는 매장이여서 편안하게 갔다왔습니다 추천해드려요!',
    heart: 1,
    commentCount: 1,
    comments: [],
    owner: {
      _id: '123124',
      email: 'email.gmail.com',
      avatarUrl: '..',
      name: '강아지주인',
      __v: unique,
    },
    createdAt: new Date(2022, 3, 23, 18, 22),
    __v: unique++,
  },
  {
    _id: String(unique),
    title: '타이틀',
    category: '숙소',
    city: '서울',
    detailCity: '마포동',
    tags: '#숙소#행복#편안#꿀잼',
    contents:
      '![imageURL](https://meongmeong-tui-img-storage.s3-ap-northeast-2.amazonaws.com/8a38540c-fc7c-461c-96b7-268dc9c6d29e.jpeg)전문강사님께서 반려동물을 맡아주시는 숙소가 있습니다! 추가비용도 얼마안해서 부담없이 편하게 잘 다녀왔습니다. 아이들도 행복해보였어요!',
    heart: 1,
    commentCount: 1,
    comments: [],
    owner: {
      _id: '123124',
      email: 'email.gmail.com',
      avatarUrl: '..',
      name: '고양이주인',
      __v: unique,
    },
    createdAt: new Date(2022, 3, 23, 18, 22),
    __v: unique++,
  },
  {
    _id: String(unique),
    title: '타이틀',
    category: '기타',
    city: '인천',
    detailCity: '부평',
    tags: '#산책#공부#벤치',
    contents:
      '![imageURL](https://meongmeong-tui-img-storage.s3-ap-northeast-2.amazonaws.com/d0711b4c-25e3-44c1-bf9f-ff1d38be316b.jpeg)너무 좋은곳을 발견했는데, 저 혼자 알기 아쉬워서 공유하고자 글을 올리게 되었습니다. 강아지들이 너무 좋아하는 산책로에요! 인천 부평구입니다',
    heart: 1,
    commentCount: 1,
    comments: [],
    owner: {
      _id: '123124',
      email: 'email.gmail.com',
      avatarUrl: '..',
      name: '반려동물장인',
      __v: unique,
    },
    createdAt: new Date(2022, 3, 23, 18, 22),
    __v: unique++,
  },
  {
    _id: String(unique),
    title: '너무 재미있는 여행이였어요',
    category: '여행',
    city: '경기',
    detailCity: '군포',
    tags: '#여행#경기#군포',
    contents:
      '![imageURL](https://meongmeong-tui-img-storage.s3-ap-northeast-2.amazonaws.com/d0711b4c-25e3-44c1-bf9f-ff1d38be316b.jpeg)경기도 군포시에 있는곳에 여행을 갔다왔는데, 정말 재밌었습니다. 주변에 한세대학교라는 학교도 있고, 가면서 먹은 타코야끼도 굉장히 맛있었습니다. 산책하기 좋은 공원도 있더라구요',
    heart: 1,
    commentCount: 1,
    comments: [],
    owner: {
      _id: '123124',
      email: 'email.gmail.com',
      avatarUrl: '..',
      name: '지나가는학생',
      __v: unique,
    },
    createdAt: new Date(2022, 4, 15, 20, 42),
    __v: unique++,
  },
  {
    _id: String(unique),
    title: '대구 괜찮은 음식점',
    category: '음식점',
    city: '대구',
    detailCity: '북구',
    tags: '#대구#북구#꿀맛',
    contents:
      '![imageURL](https://meongmeong-tui-img-storage.s3-ap-northeast-2.amazonaws.com/d0711b4c-25e3-44c1-bf9f-ff1d38be316b.jpeg)강아지 출입을 허용하는 매장이 있어서 공유해드리고자 글을 올립니다 추천해드려요!',
    heart: 1,
    commentCount: 1,
    comments: [],
    owner: {
      _id: '123124',
      email: 'email.gmail.com',
      avatarUrl: '..',
      name: '인천사는집사',
      __v: unique,
    },
    createdAt: new Date(2022, 4, 18, 20, 52),
    __v: unique++,
  },
  {
    _id: String(unique),
    title: '인천에있는 강아지 출입가능 숙소에 다녀왔습니다',
    category: '숙소',
    city: '인천',
    detailCity: '간석동',
    tags: '#숙소#행복#편안#꿀잼',
    contents:
      '![imageURL](https://meongmeong-tui-img-storage.s3-ap-northeast-2.amazonaws.com/d0711b4c-25e3-44c1-bf9f-ff1d38be316b.jpeg)고양이 전용 숙소가 있다는데 다들 알고 계셨나요? 인천 간석동에 위치한 곳입니다 공유해드려요!',
    heart: 1,
    commentCount: 1,
    comments: [],
    owner: {
      _id: '123124',
      email: 'email.gmail.com',
      avatarUrl: '..',
      name: '강아지최고',
      __v: unique,
    },
    createdAt: new Date(2022, 4, 19, 20, 3),
    __v: unique++,
  },
  {
    _id: String(unique),
    title: '타이틀',
    category: '기타',
    city: '경기',
    detailCity: '군포',
    tags: '#산책#벤치#커피#카페',
    contents:
      '![imageURL](https://meongmeong-tui-img-storage.s3-ap-northeast-2.amazonaws.com/8a38540c-fc7c-461c-96b7-268dc9c6d29e.jpeg)경기도 군포시에 산책할만한 곳이 있네요! 타코야끼도 맛있고 주변에 한세대학교 축제를 하길래 너무 재밌었습니다!',
    heart: 1,
    commentCount: 1,
    comments: [],
    owner: {
      _id: '123124',
      email: 'email.gmail.com',
      avatarUrl: '..',
      name: '고양이최고',
      __v: unique,
    },
    createdAt: new Date(2022, 4, 11, 20, 3),
    __v: unique++,
  },
  {
    _id: String(unique),
    title: '여행을 다녀왔습니다',
    category: '여행',
    city: '대구',
    detailCity: '북구',
    tags: '#여행#추억#꿀잼#대구#인천',
    contents:
      '![imageURL](https://meongmeong-tui-img-storage.s3-ap-northeast-2.amazonaws.com/8a38540c-fc7c-461c-96b7-268dc9c6d29e.jpeg)너무 재밌고 기분좋았던 여행지를 추천해드리고자 게시글을 작성하게 되었습니다~',
    heart: 1,
    commentCount: 1,
    comments: [],
    owner: {
      _id: '123124',
      email: 'email.gmail.com',
      avatarUrl: '..',
      name: '강아지고양이',
      __v: unique,
    },
    createdAt: new Date(2022, 4, 16, 20, 42),
    __v: unique++,
  },
  {
    _id: String(unique),
    title: '타이틀',
    category: '음식점',
    city: '서울',
    detailCity: '홍대',
    tags: '#맛집#대박#서울#홍대',
    contents:
      '![imageURL](https://meongmeong-tui-img-storage.s3-ap-northeast-2.amazonaws.com/8a38540c-fc7c-461c-96b7-268dc9c6d29e.jpeg)홍대쪽에 놀러갈일이 있어서 반려동물을 데리고 갔는데 너무 맛있고, 가성비 좋은 식당이 있어서 소개해드립니다!!',
    heart: 1,
    commentCount: 1,
    comments: [],
    owner: {
      _id: '123124',
      email: 'email.gmail.com',
      avatarUrl: '..',
      name: '주인또는집사',
      __v: unique,
    },
    createdAt: new Date(2022, 4, 20, 20, 52),
    __v: unique++,
  },
  {
    _id: String(unique),
    title: '타이틀',
    category: '숙소',
    city: '경기',
    detailCity: '군포',
    tags: '#숙소#행복#경기#군포',
    contents:
      '![imageURL](https://meongmeong-tui-img-storage.s3-ap-northeast-2.amazonaws.com/8a38540c-fc7c-461c-96b7-268dc9c6d29e.jpeg)숙소를 알아보던 도중 반려동물을 같이 데려갈 수 있는곳이 있더라구요! 정말 잘됐습니다 저는 반려동물과 함께 행복한 시간을 보냈답니다!',
    heart: 1,
    commentCount: 1,
    comments: [],
    owner: {
      _id: '123124',
      email: 'email.gmail.com',
      avatarUrl: '..',
      name: '주인또는집사',
      __v: unique,
    },
    createdAt: new Date(2022, 4, 20, 20, 3),
    __v: unique++,
  },
  {
    _id: String(unique),
    title: '타이틀',
    category: '기타',
    city: '서울',
    detailCity: '한강',
    tags: '#산책#공원#운동',
    contents:
      '![imageURL](https://meongmeong-tui-img-storage.s3-ap-northeast-2.amazonaws.com/6123faf9-b861-48da-8152-15cbafa67a37.jpeg)서울 한강은 역시 산책하기에 너무 좋은곳인것 같아요 다들 아실거라고 생각합니다',
    heart: 1,
    commentCount: 1,
    comments: [],
    owner: {
      _id: '123124',
      email: 'email.gmail.com',
      avatarUrl: '..',
      name: '주인또는집사',
      __v: unique,
    },
    createdAt: new Date(2022, 4, 15, 20, 3),
    __v: unique++,
  },
  {
    _id: String(unique),
    title: '진짜 행복한 추억을 남겼네요',
    category: '여행',
    city: '부산',
    detailCity: '해운대',
    tags: '#여행#부산#바다#추억',
    contents:
      '![imageURL](https://meongmeong-tui-img-storage.s3-ap-northeast-2.amazonaws.com/6123faf9-b861-48da-8152-15cbafa67a37.jpeg)부산광역시 해운대에 놀러갔다왔어요! 강아지들이 너무 행복해했고 저도 그 모습을 보면서 너무 행복했습니다~',
    heart: 1,
    commentCount: 1,
    comments: [],
    owner: {
      _id: '123124',
      email: 'email.gmail.com',
      avatarUrl: '..',
      name: '주인또는집사',
      __v: unique,
    },
    createdAt: new Date(2022, 4, 21, 20, 42),
    __v: unique++,
  },
  {
    _id: String(unique),
    title: '타이틀',
    category: '음식점',
    city: '인천',
    detailCity: '구월동',
    tags: '#맛집#튀김#편안',
    contents:
      '![imageURL](https://meongmeong-tui-img-storage.s3-ap-northeast-2.amazonaws.com/6123faf9-b861-48da-8152-15cbafa67a37.jpeg)위치는 인천 구월동이고 튀김맛집을 갔다왔습니다! 강아지 전용 밥도 따로 판매하셔서 너무 좋았습니다!',
    heart: 1,
    commentCount: 1,
    comments: [],
    owner: {
      _id: '123124',
      email: 'email.gmail.com',
      avatarUrl: '..',
      name: '주인또는집사',
      __v: unique,
    },
    createdAt: new Date(2022, 4, 22, 20, 52),
    __v: unique++,
  },
  {
    _id: String(unique),
    title: '타이틀',
    category: '숙소',
    city: '서울',
    detailCity: '마포동',
    tags: '#숙소#행복#편안#꿀잼',
    contents:
      '![imageURL](https://meongmeong-tui-img-storage.s3-ap-northeast-2.amazonaws.com/6123faf9-b861-48da-8152-15cbafa67a37.jpeg)강아지를 데리고 갈 수 있는 숙박시설이 있더라구요! 서울 마포동에 위치한 곳입니다. 너무 좋았어요',
    heart: 1,
    commentCount: 1,
    comments: [],
    owner: {
      _id: '123124',
      email: 'email.gmail.com',
      avatarUrl: '..',
      name: '주인또는집사',
      __v: unique,
    },
    createdAt: new Date(2022, 4, 23, 20, 3),
    __v: unique++,
  },
  {
    _id: String(unique),
    title: '타이틀',
    category: '기타',
    city: '인천',
    detailCity: '부평',
    tags: '#산책#공부#벤치',
    contents:
      '![imageURL](https://meongmeong-tui-img-storage.s3-ap-northeast-2.amazonaws.com/cfb4b071-c273-4b05-9dbc-3cc4bf5e6ca5.jpeg)산책할만한곳이 어디있나 찾아보던 도중 인천 부평구에 괜찮은곳이 있어서 공유해드립니다',
    heart: 1,
    commentCount: 1,
    comments: [],
    owner: {
      _id: '123124',
      email: 'email.gmail.com',
      avatarUrl: '..',
      name: '주인또는집사',
      __v: unique,
    },
    createdAt: new Date(2022, 4, 28, 2, 2),
    __v: unique++,
  },
  {
    _id: String(unique),
    title: '여행을 다녀왔습니다',
    category: '여행',
    city: '인천',
    detailCity: '부평',
    tags: '#여행#추억#꿀잼#인천',
    contents:
      '![imageURL](https://meongmeong-tui-img-storage.s3-ap-northeast-2.amazonaws.com/c1f863de-9507-44f0-9287-a67aa2dcefa3.jpeg)너무너무 재밌는 하루였어요! 우리 이쁜 아이들좀 보세요!!!',
    heart: 1,
    commentCount: 1,
    comments: [],
    owner: {
      _id: '123124',
      email: 'email.gmail.com',
      avatarUrl: '..',
      name: '주인또는집사',
      __v: unique,
    },
    createdAt: new Date(2022, 5, 10, 20, 42),
    __v: unique++,
  },
  {
    _id: String(unique),
    title: '경기 괜찮은 음식점',
    category: '음식점',
    city: '경기',
    detailCity: '군포',
    tags: '#경기#군포#북구#꿀맛',
    contents:
      '![imageURL](https://meongmeong-tui-img-storage.s3-ap-northeast-2.amazonaws.com/c1f863de-9507-44f0-9287-a67aa2dcefa3.jpeg)경기도 군포시에 있는 돈가스 전문점에 갔다왔는데 강아지 출입을 허용하는 매장이여서 편안하게 갔다왔습니다 추천해드려요!',
    heart: 1,
    commentCount: 1,
    comments: [],
    owner: {
      _id: '123124',
      email: 'email.gmail.com',
      avatarUrl: '..',
      name: '주인또는집사',
      __v: unique,
    },
    createdAt: new Date(2022, 5, 8, 20, 52),
    __v: unique++,
  },
  {
    _id: String(unique),
    title: '대구에있는 강아지 출입가능 숙소에 다녀왔습니다',
    category: '숙소',
    city: '대구',
    detailCity: '북구',
    tags: '#숙소#행복#편안#꿀잼',
    contents:
      '![imageURL](https://meongmeong-tui-img-storage.s3-ap-northeast-2.amazonaws.com/fb014886-a283-457e-8fdc-7f8071f92499.jpeg)반려동물을 맡겨달라고 숙소에 미리 전화로 예약해두면, 전문강사님께서 맡아주시더라구요! 추가비용도 얼마안해서 부담없이 편하게 잘 다녀왔습니다. 아이들도 행복해보였어요!',
    heart: 1,
    commentCount: 1,
    comments: [],
    owner: {
      _id: '123124',
      email: 'email.gmail.com',
      avatarUrl: '..',
      name: '주인또는집사',
      __v: unique,
    },
    createdAt: new Date(2022, 5, 4, 20, 3),
    __v: unique++,
  },
  {
    _id: String(unique),
    title: '타이틀',
    category: '기타',
    city: '부산',
    detailCity: '해운대',
    tags: '#산책#벤치#커피#카페#바다',
    contents:
      '![imageURL](https://meongmeong-tui-img-storage.s3-ap-northeast-2.amazonaws.com/fb014886-a283-457e-8fdc-7f8071f92499.jpeg)부산광역시에 공부하기 편한 벤치가 있더라구요! 주변에 카페도있고 커피마시면서 강아지 산책시키기에도 너무 좋은것 같아서 공유해드립니다!',
    heart: 1,
    commentCount: 1,
    comments: [],
    owner: {
      _id: '123124',
      email: 'email.gmail.com',
      avatarUrl: '..',
      name: '주인또는집사',
      __v: unique,
    },
    createdAt: new Date(2022, 5, 2, 2, 2),
    __v: unique++,
  },
  {
    _id: String(unique),
    title: '너무 재미있는 여행이였어요',
    category: '여행',
    city: '대구',
    detailCity: '북구',
    tags: '#여행#대구#북구',
    contents:
      '![imageURL](https://meongmeong-tui-img-storage.s3-ap-northeast-2.amazonaws.com/fb014886-a283-457e-8fdc-7f8071f92499.jpeg)대구에 여행을 갔다왔습니다. 카운터에 문의 후 반려동물을 데려갔는데 데려가서 케어해주시더라구요! 너무 좋았습니다',
    heart: 1,
    commentCount: 1,
    comments: [],
    owner: {
      _id: '123124',
      email: 'email.gmail.com',
      avatarUrl: '..',
      name: '강아지고양이',
      __v: unique,
    },
    createdAt: new Date(2022, 2, 20, 2, 3),
    __v: unique++,
  },

  {
    _id: String(unique),
    title: '타이틀',
    category: '음식점',
    city: '서울',
    detailCity: '홍대',
    tags: '#맛집#대박#서울#홍대',
    contents:
      '![imageURL](https://meongmeong-tui-img-storage.s3-ap-northeast-2.amazonaws.com/fb014886-a283-457e-8fdc-7f8071f92499.jpeg)진짜 맛있는 맛집이 있는데 소개해드릴려고 합니다! 반려동물도 같이 들어갈수있대요! 너무 좋았습니다',
    heart: 1,
    commentCount: 1,
    comments: [],
    owner: {
      _id: '123124',
      email: 'email.gmail.com',
      avatarUrl: '..',
      name: '강아지고양이',
      __v: unique,
    },
    createdAt: new Date(2022, 2, 20, 2, 3),
    __v: unique++,
  },
  {
    _id: String(unique),
    title: '타이틀',
    category: '숙소',
    city: '경기',
    detailCity: '군포',
    tags: '#숙소#행복#경기#군포',
    contents:
      '![imageURL](https://meongmeong-tui-img-storage.s3-ap-northeast-2.amazonaws.com/37dd23e7-bf4d-4673-b726-7bb628220b82.jpeg)숙소를 알아봤는데, 반려동물도 출입이 가능한곳이 있더라구요! 정말 잘됐습니다 저는 반려동물과 함께 행복한 시간을 보냈답니다!',
    heart: 1,
    commentCount: 1,
    comments: [],
    owner: {
      _id: '123124',
      email: 'email.gmail.com',
      avatarUrl: '..',
      name: '강아지고양이',
      __v: unique,
    },
    createdAt: new Date(2022, 2, 20, 2, 3),
    __v: unique++,
  },
  {
    _id: String(unique),
    title: '타이틀',
    category: '기타',
    city: '서울',
    detailCity: '마포동',
    tags: '#산책#공원#운동',
    contents:
      '![imageURL](https://meongmeong-tui-img-storage.s3-ap-northeast-2.amazonaws.com/37dd23e7-bf4d-4673-b726-7bb628220b82.jpeg)서울 마포동에 위치한 산책로인데, 다른사람들과 공유하고 싶어서 글을 올립니다 여기 되게 좋아요!',
    heart: 1,
    commentCount: 1,
    comments: [],
    owner: {
      _id: '123124',
      email: 'email.gmail.com',
      avatarUrl: '..',
      name: '강아지고양이',
      __v: unique,
    },
    createdAt: new Date(2022, 2, 20, 2, 2),
    __v: unique++,
  },
  {
    _id: String(unique),
    title: '진짜 행복한 추억을 남겼네요',
    category: '여행',
    city: '부산',
    detailCity: '해운대',
    tags: '#여행#부산#바다#추억',
    contents:
      '![imageURL](https://meongmeong-tui-img-storage.s3-ap-northeast-2.amazonaws.com/37dd23e7-bf4d-4673-b726-7bb628220b82.jpeg)강아지들과 바다보러 해운대에 갔는데 강아지들이 너무 행복해했고 저도 그 모습을 보면서 너무 행복했습니다~',
    heart: 1,
    commentCount: 1,
    comments: [],
    owner: {
      _id: '123124',
      email: 'email.gmail.com',
      avatarUrl: '..',
      name: '강아지고양이',
      __v: unique,
    },
    createdAt: new Date(2022, 3, 23, 18, 22),
    __v: unique++,
  },
  {
    _id: String(unique),
    title: '타이틀',
    category: '음식점',
    city: '인천',
    detailCity: '구월동',
    tags: '#맛집#튀김#편안',
    contents:
      '![imageURL](https://meongmeong-tui-img-storage.s3-ap-northeast-2.amazonaws.com/37dd23e7-bf4d-4673-b726-7bb628220b82.jpeg)인천 구월동에 있는 튀김 전문점에 갔다왔는데 강아지 출입을 허용하는 매장이여서 편안하게 갔다왔습니다 추천해드려요!',
    heart: 1,
    commentCount: 1,
    comments: [],
    owner: {
      _id: '123124',
      email: 'email.gmail.com',
      avatarUrl: '..',
      name: '강아지고양이',
      __v: unique,
    },
    createdAt: new Date(2022, 3, 23, 18, 22),
    __v: unique++,
  },
  {
    _id: String(unique),
    title: '타이틀',
    category: '숙소',
    city: '서울',
    detailCity: '마포동',
    tags: '#숙소#행복#편안#꿀잼',
    contents:
      '![imageURL](https://meongmeong-tui-img-storage.s3-ap-northeast-2.amazonaws.com/1c208a4b-5c5e-470d-aa81-2c9a762bd66a.jpeg)전문강사님께서 반려동물을 맡아주시는 숙소가 있습니다! 추가비용도 얼마안해서 부담없이 편하게 잘 다녀왔습니다. 아이들도 행복해보였어요!',
    heart: 1,
    commentCount: 1,
    comments: [],
    owner: {
      _id: '123124',
      email: 'email.gmail.com',
      avatarUrl: '..',
      name: '강아지고양이',
      __v: unique,
    },
    createdAt: new Date(2022, 3, 23, 18, 22),
    __v: unique++,
  },
  {
    _id: String(unique),
    title: '타이틀',
    category: '기타',
    city: '인천',
    detailCity: '부평',
    tags: '#산책#공부#벤치',
    contents:
      '![imageURL](https://meongmeong-tui-img-storage.s3-ap-northeast-2.amazonaws.com/1c208a4b-5c5e-470d-aa81-2c9a762bd66a.jpeg)너무 좋은곳을 발견했는데, 저 혼자 알기 아쉬워서 공유하고자 글을 올리게 되었습니다. 강아지들이 너무 좋아하는 산책로에요! 인천 부평구입니다',
    heart: 1,
    commentCount: 1,
    comments: [],
    owner: {
      _id: '123124',
      email: 'email.gmail.com',
      avatarUrl: '..',
      name: '강아지고양이',
      __v: unique,
    },
    createdAt: new Date(2022, 3, 23, 18, 22),
    __v: unique++,
  },
  {
    _id: String(unique),
    title: '너무 재미있는 여행이였어요',
    category: '여행',
    city: '경기',
    detailCity: '군포',
    tags: '#여행#경기#군포',
    contents:
      '![imageURL](https://meongmeong-tui-img-storage.s3-ap-northeast-2.amazonaws.com/1c208a4b-5c5e-470d-aa81-2c9a762bd66a.jpeg)경기도 군포시에 있는곳에 여행을 갔다왔는데, 정말 재밌었습니다. 주변에 한세대학교라는 학교도 있고, 가면서 먹은 타코야끼도 굉장히 맛있었습니다. 산책하기 좋은 공원도 있더라구요',
    heart: 1,
    commentCount: 1,
    comments: [],
    owner: {
      _id: '123124',
      email: 'email.gmail.com',
      avatarUrl: '..',
      name: '강아지고양이',
      __v: unique,
    },
    createdAt: new Date(2022, 4, 15, 20, 42),
    __v: unique++,
  },
  {
    _id: String(unique),
    title: '대구 괜찮은 음식점',
    category: '음식점',
    city: '대구',
    detailCity: '북구',
    tags: '#대구#북구#꿀맛',
    contents:
      '![imageURL](https://meongmeong-tui-img-storage.s3-ap-northeast-2.amazonaws.com/f102f37f-1c79-4a75-b9be-6bf9ce46995a.jpeg)강아지 출입을 허용하는 매장이 있어서 공유해드리고자 글을 올립니다 추천해드려요!',
    heart: 1,
    commentCount: 1,
    comments: [],
    owner: {
      _id: '123124',
      email: 'email.gmail.com',
      avatarUrl: '..',
      name: '강아지고양이',
      __v: unique,
    },
    createdAt: new Date(2022, 4, 18, 20, 52),
    __v: unique++,
  },
  {
    _id: String(unique),
    title: '인천에있는 강아지 출입가능 숙소에 다녀왔습니다',
    category: '숙소',
    city: '인천',
    detailCity: '간석동',
    tags: '#숙소#행복#편안#꿀잼',
    contents:
      '![imageURL](https://meongmeong-tui-img-storage.s3-ap-northeast-2.amazonaws.com/e54a52c7-9685-46f8-b8a1-54da3ccfc1e3.jpeg)고양이 전용 숙소가 있다는데 다들 알고 계셨나요? 인천 간석동에 위치한 곳입니다 공유해드려요!',
    heart: 1,
    commentCount: 1,
    comments: [],
    owner: {
      _id: '123124',
      email: 'email.gmail.com',
      avatarUrl: '..',
      name: '강아지고양이',
      __v: unique,
    },
    createdAt: new Date(2022, 4, 19, 20, 3),
    __v: unique++,
  },
  {
    _id: String(unique),
    title: '타이틀',
    category: '기타',
    city: '경기',
    detailCity: '군포',
    tags: '#산책#벤치#커피#카페',
    contents:
      '![imageURL](https://meongmeong-tui-img-storage.s3-ap-northeast-2.amazonaws.com/e54a52c7-9685-46f8-b8a1-54da3ccfc1e3.jpeg)경기도 군포시에 산책할만한 곳이 있네요! 타코야끼도 맛있고 주변에 한세대학교 축제를 하길래 너무 재밌었습니다!',
    heart: 1,
    commentCount: 1,
    comments: [],
    owner: {
      _id: '123124',
      email: 'email.gmail.com',
      avatarUrl: '..',
      name: '고재민',
      __v: unique,
    },
    createdAt: new Date(2022, 4, 11, 20, 3),
    __v: unique++,
  },
  {
    _id: String(unique),
    title: '여행을 다녀왔습니다',
    category: '여행',
    city: '대구',
    detailCity: '북구',
    tags: '#여행#추억#꿀잼#대구#인천',
    contents:
      '![imageURL](https://meongmeong-tui-img-storage.s3-ap-northeast-2.amazonaws.com/f44fd0b4-9bd2-4a62-97a3-924c24cd1075.jpeg)너무 재밌고 기분좋았던 여행지를 추천해드리고자 게시글을 작성하게 되었습니다~',
    heart: 1,
    commentCount: 1,
    comments: [],
    owner: {
      _id: '123124',
      email: 'email.gmail.com',
      avatarUrl: '..',
      name: '고재민',
      __v: unique,
    },
    createdAt: new Date(2022, 4, 16, 20, 42),
    __v: unique++,
  },
  {
    _id: String(unique),
    title: '타이틀',
    category: '음식점',
    city: '서울',
    detailCity: '홍대',
    tags: '#맛집#대박#서울#홍대',
    contents:
      '![imageURL](https://meongmeong-tui-img-storage.s3-ap-northeast-2.amazonaws.com/f102f37f-1c79-4a75-b9be-6bf9ce46995a.jpeg)홍대쪽에 놀러갈일이 있어서 반려동물을 데리고 갔는데 너무 맛있고, 가성비 좋은 식당이 있어서 소개해드립니다!!',
    heart: 1,
    commentCount: 1,
    comments: [],
    owner: {
      _id: '123124',
      email: 'email.gmail.com',
      avatarUrl: '..',
      name: '고재민',
      __v: unique,
    },
    createdAt: new Date(2022, 4, 20, 20, 52),
    __v: unique++,
  },
  {
    _id: String(unique),
    title: '타이틀',
    category: '숙소',
    city: '경기',
    detailCity: '군포',
    tags: '#숙소#행복#경기#군포',
    contents:
      '![imageURL](https://meongmeong-tui-img-storage.s3-ap-northeast-2.amazonaws.com/1c208a4b-5c5e-470d-aa81-2c9a762bd66a.jpeg)숙소를 알아보던 도중 반려동물을 같이 데려갈 수 있는곳이 있더라구요! 정말 잘됐습니다 저는 반려동물과 함께 행복한 시간을 보냈답니다!',
    heart: 1,
    commentCount: 1,
    comments: [],
    owner: {
      _id: '123124',
      email: 'email.gmail.com',
      avatarUrl: '..',
      name: '고재민',
      __v: unique,
    },
    createdAt: new Date(2022, 4, 20, 20, 3),
    __v: unique++,
  },
  {
    _id: String(unique),
    title: '타이틀',
    category: '기타',
    city: '서울',
    detailCity: '한강',
    tags: '#산책#공원#운동',
    contents:
      '![imageURL](https://meongmeong-tui-img-storage.s3-ap-northeast-2.amazonaws.com/cfb4b071-c273-4b05-9dbc-3cc4bf5e6ca5.jpeg)서울 한강은 역시 산책하기에 너무 좋은곳인것 같아요 다들 아실거라고 생각합니다',
    heart: 1,
    commentCount: 1,
    comments: [],
    owner: {
      _id: '123124',
      email: 'email.gmail.com',
      avatarUrl: '..',
      name: '고재민',
      __v: unique,
    },
    createdAt: new Date(2022, 4, 15, 20, 3),
    __v: unique++,
  },
  {
    _id: String(unique),
    title: '진짜 행복한 추억을 남겼네요',
    category: '여행',
    city: '부산',
    detailCity: '해운대',
    tags: '#여행#부산#바다#추억',
    contents:
      '부산광역시 해운대에 놀러갔다왔어요! 강아지들이 너무 행복해했고 저도 그 모습을 보면서 너무 행복했습니다~',
    heart: 1,
    commentCount: 1,
    comments: [],
    owner: {
      _id: '123124',
      email: 'email.gmail.com',
      avatarUrl: '..',
      name: '고재민',
      __v: unique,
    },
    createdAt: new Date(2022, 4, 21, 20, 42),
    __v: unique++,
  },
  {
    _id: String(unique),
    title: '타이틀',
    category: '음식점',
    city: '인천',
    detailCity: '구월동',
    tags: '#맛집#튀김#편안',
    contents:
      '위치는 인천 구월동이고 튀김맛집을 갔다왔습니다! 강아지 전용 밥도 따로 판매하셔서 너무 좋았습니다!',
    heart: 1,
    commentCount: 1,
    comments: [],
    owner: {
      _id: '123124',
      email: 'email.gmail.com',
      avatarUrl: '..',
      name: '고재민',
      __v: unique,
    },
    createdAt: new Date(2022, 4, 22, 20, 52),
    __v: unique++,
  },
  {
    _id: String(unique),
    title: '타이틀',
    category: '숙소',
    city: '서울',
    detailCity: '마포동',
    tags: '#숙소#행복#편안#꿀잼',
    contents:
      '강아지를 데리고 갈 수 있는 숙박시설이 있더라구요! 서울 마포동에 위치한 곳입니다. 너무 좋았어요',
    heart: 1,
    commentCount: 1,
    comments: [],
    owner: {
      _id: '123124',
      email: 'email.gmail.com',
      avatarUrl: '..',
      name: '고재민',
      __v: unique,
    },
    createdAt: new Date(2022, 4, 23, 20, 3),
    __v: unique++,
  },
  {
    _id: String(unique),
    title: '타이틀',
    category: '기타',
    city: '인천',
    detailCity: '부평',
    tags: '#산책#공부#벤치',
    contents:
      '산책할만한곳이 어디있나 찾아보던 도중 인천 부평구에 괜찮은곳이 있어서 공유해드립니다',
    heart: 1,
    commentCount: 1,
    comments: [],
    owner: {
      _id: '123124',
      email: 'email.gmail.com',
      avatarUrl: '..',
      name: '고재민',
      __v: unique,
    },
    createdAt: new Date(2022, 4, 28, 2, 2),
    __v: unique++,
  },
  {
    _id: String(unique),
    title: '여행을 다녀왔습니다',
    category: '여행',
    city: '인천',
    detailCity: '부평',
    tags: '#여행#추억#꿀잼#인천',
    contents:
      '![imageURL](https://meongmeong-tui-img-storage.s3-ap-northeast-2.amazonaws.com/c1f863de-9507-44f0-9287-a67aa2dcefa3.jpeg)너무너무 재밌는 하루였어요! 우리 이쁜 아이들좀 보세요!!!',
    heart: 1,
    commentCount: 1,
    comments: [],
    owner: {
      _id: '123124',
      email: 'email.gmail.com',
      avatarUrl: '..',
      name: '고재민',
      __v: unique,
    },
    createdAt: new Date(2022, 5, 10, 20, 42),
    __v: unique++,
  },
  {
    _id: String(unique),
    title: '경기 괜찮은 음식점',
    category: '음식점',
    city: '경기',
    detailCity: '군포',
    tags: '#경기#군포#북구#꿀맛',
    contents:
      '![imageURL](https://meongmeong-tui-img-storage.s3-ap-northeast-2.amazonaws.com/fb014886-a283-457e-8fdc-7f8071f92499.jpeg)경기도 군포시에 있는 돈가스 전문점에 갔다왔는데 강아지 출입을 허용하는 매장이여서 편안하게 갔다왔습니다 추천해드려요!',
    heart: 1,
    commentCount: 1,
    comments: [],
    owner: {
      _id: '123124',
      email: 'email.gmail.com',
      avatarUrl: '..',
      name: '윤운일',
      __v: unique,
    },
    createdAt: new Date(2022, 5, 8, 20, 52),
    __v: unique++,
  },
  {
    _id: String(unique),
    title: '대구에있는 강아지 출입가능 숙소에 다녀왔습니다',
    category: '숙소',
    city: '대구',
    detailCity: '북구',
    tags: '#숙소#행복#편안#꿀잼',
    contents:
      '![imageURL](https://meongmeong-tui-img-storage.s3-ap-northeast-2.amazonaws.com/8bdcd74e-1c6a-4e4c-be92-ac0e61e31c9c.jpeg)반려동물을 맡겨달라고 숙소에 미리 전화로 예약해두면, 전문강사님께서 맡아주시더라구요! 추가비용도 얼마안해서 부담없이 편하게 잘 다녀왔습니다. 아이들도 행복해보였어요!',
    heart: 1,
    commentCount: 1,
    comments: [],
    owner: {
      _id: '123124',
      email: 'email.gmail.com',
      avatarUrl: '..',
      name: '윤운일',
      __v: unique,
    },
    createdAt: new Date(2022, 5, 4, 20, 3),
    __v: unique++,
  },
  {
    _id: String(unique),
    title: '타이틀',
    category: '기타',
    city: '부산',
    detailCity: '해운대',
    tags: '#산책#벤치#커피#카페#바다',
    contents:
      '![imageURL](https://meongmeong-tui-img-storage.s3-ap-northeast-2.amazonaws.com/dcb35e89-1ffe-43c3-a5c6-a00b7d9a84f2.jpeg)부산광역시에 공부하기 편한 벤치가 있더라구요! 주변에 카페도있고 커피마시면서 강아지 산책시키기에도 너무 좋은것 같아서 공유해드립니다!',
    heart: 1,
    commentCount: 1,
    comments: [],
    owner: {
      _id: '123124',
      email: 'email.gmail.com',
      avatarUrl: '..',
      name: '윤운일',
      __v: unique,
    },
    createdAt: new Date(2022, 5, 2, 2, 2),
    __v: unique++,
  },
  {
    _id: String(unique),
    title: '너무 재미있는 여행이였어요',
    category: '여행',
    city: '대구',
    detailCity: '북구',
    tags: '#여행#대구#북구',
    contents:
      '![imageURL](https://meongmeong-tui-img-storage.s3-ap-northeast-2.amazonaws.com/9c7e76ac-cc24-4593-9700-ec503dd3402c.jpeg)대구에 여행을 갔다왔습니다. 카운터에 문의 후 반려동물을 데려갔는데 데려가서 케어해주시더라구요! 너무 좋았습니다',
    heart: 1,
    commentCount: 1,
    comments: [],
    owner: {
      _id: '123124',
      email: 'email.gmail.com',
      avatarUrl: '..',
      name: '윤운일',
      __v: unique,
    },
    createdAt: new Date(2022, 2, 20, 2, 3),
    __v: unique++,
  },

  {
    _id: String(unique),
    title: '타이틀',
    category: '음식점',
    city: '서울',
    detailCity: '홍대',
    tags: '#맛집#대박#서울#홍대',
    contents:
      '![imageURL](https://meongmeong-tui-img-storage.s3-ap-northeast-2.amazonaws.com/6123faf9-b861-48da-8152-15cbafa67a37.jpeg)진짜 맛있는 맛집이 있는데 소개해드릴려고 합니다! 반려동물도 같이 들어갈수있대요! 너무 좋았습니다',
    heart: 1,
    commentCount: 1,
    comments: [],
    owner: {
      _id: '123124',
      email: 'email.gmail.com',
      avatarUrl: '..',
      name: '윤운일',
      __v: unique,
    },
    createdAt: new Date(2022, 2, 20, 2, 3),
    __v: unique++,
  },
  {
    _id: String(unique),
    title: '타이틀',
    category: '숙소',
    city: '경기',
    detailCity: '군포',
    tags: '#숙소#행복#경기#군포',
    contents:
      '![imageURL](https://meongmeong-tui-img-storage.s3-ap-northeast-2.amazonaws.com/d0711b4c-25e3-44c1-bf9f-ff1d38be316b.jpeg)숙소를 알아봤는데, 반려동물도 출입이 가능한곳이 있더라구요! 정말 잘됐습니다 저는 반려동물과 함께 행복한 시간을 보냈답니다!',
    heart: 1,
    commentCount: 1,
    comments: [],
    owner: {
      _id: '123124',
      email: 'email.gmail.com',
      avatarUrl: '..',
      name: '윤운일',
      __v: unique,
    },
    createdAt: new Date(2022, 2, 20, 2, 3),
    __v: unique++,
  },
  {
    _id: String(unique),
    title: '타이틀',
    category: '기타',
    city: '서울',
    detailCity: '마포동',
    tags: '#산책#공원#운동',
    contents:
      '![imageURL](https://meongmeong-tui-img-storage.s3-ap-northeast-2.amazonaws.com/8a38540c-fc7c-461c-96b7-268dc9c6d29e.jpeg)서울 마포동에 위치한 산책로인데, 다른사람들과 공유하고 싶어서 글을 올립니다 여기 되게 좋아요!',
    heart: 1,
    commentCount: 1,
    comments: [],
    owner: {
      _id: '123124',
      email: 'email.gmail.com',
      avatarUrl: '..',
      name: '윤운일',
      __v: unique,
    },
    createdAt: new Date(2022, 2, 20, 2, 2),
    __v: unique++,
  },
  {
    _id: String(unique),
    title: '진짜 행복한 추억을 남겼네요',
    category: '여행',
    city: '부산',
    detailCity: '해운대',
    tags: '#여행#부산#바다#추억',
    contents:
      '![imageURL](https://meongmeong-tui-img-storage.s3-ap-northeast-2.amazonaws.com/04d73daa-0d66-4228-a784-2320a703ad69.jpeg)강아지들과 바다보러 해운대에 갔는데 강아지들이 너무 행복해했고 저도 그 모습을 보면서 너무 행복했습니다~',
    heart: 1,
    commentCount: 1,
    comments: [],
    owner: {
      _id: '123124',
      email: 'email.gmail.com',
      avatarUrl: '..',
      name: '윤운일',
      __v: unique,
    },
    createdAt: new Date(2022, 3, 23, 18, 22),
    __v: unique++,
  },
  {
    _id: String(unique),
    title: '타이틀',
    category: '음식점',
    city: '인천',
    detailCity: '구월동',
    tags: '#맛집#튀김#편안',
    contents:
      '![imageURL](https://meongmeong-tui-img-storage.s3-ap-northeast-2.amazonaws.com/090d2edc-57de-4ebe-857b-82406639f22c.jpeg)인천 구월동에 있는 튀김 전문점에 갔다왔는데 강아지 출입을 허용하는 매장이여서 편안하게 갔다왔습니다 추천해드려요!',
    heart: 1,
    commentCount: 1,
    comments: [],
    owner: {
      _id: '123124',
      email: 'email.gmail.com',
      avatarUrl: '..',
      name: '박상훈',
      __v: unique,
    },
    createdAt: new Date(2022, 3, 23, 18, 22),
    __v: unique++,
  },
  {
    _id: String(unique),
    title: '타이틀',
    category: '숙소',
    city: '서울',
    detailCity: '마포동',
    tags: '#숙소#행복#편안#꿀잼',
    contents:
      '![imageURL](https://meongmeong-tui-img-storage.s3-ap-northeast-2.amazonaws.com/4c335196-d5ca-48d5-8016-647595f775df.jpeg)전문강사님께서 반려동물을 맡아주시는 숙소가 있습니다! 추가비용도 얼마안해서 부담없이 편하게 잘 다녀왔습니다. 아이들도 행복해보였어요!',
    heart: 1,
    commentCount: 1,
    comments: [],
    owner: {
      _id: '123124',
      email: 'email.gmail.com',
      avatarUrl: '..',
      name: '박상훈',
      __v: unique,
    },
    createdAt: new Date(2022, 3, 23, 18, 22),
    __v: unique++,
  },
  {
    _id: String(unique),
    title: '타이틀',
    category: '기타',
    city: '인천',
    detailCity: '부평',
    tags: '#산책#공부#벤치',
    contents:
      '![imageURL](https://meongmeong-tui-img-storage.s3-ap-northeast-2.amazonaws.com/db99a0ac-a6d8-44f6-9d92-4924b5e44045.jpeg)너무 좋은곳을 발견했는데, 저 혼자 알기 아쉬워서 공유하고자 글을 올리게 되었습니다. 강아지들이 너무 좋아하는 산책로에요! 인천 부평구입니다',
    heart: 1,
    commentCount: 1,
    comments: [],
    owner: {
      _id: '123124',
      email: 'email.gmail.com',
      avatarUrl: '..',
      name: '박상훈',
      __v: unique,
    },
    createdAt: new Date(2022, 3, 23, 18, 22),
    __v: unique++,
  },
  {
    _id: String(unique),
    title: '너무 재미있는 여행이였어요',
    category: '여행',
    city: '경기',
    detailCity: '군포',
    tags: '#여행#경기#군포',
    contents:
      '![imageURL](https://meongmeong-tui-img-storage.s3-ap-northeast-2.amazonaws.com/2278d5b9-2965-47a6-9cac-36a8f82fcd59.jpeg)경기도 군포시에 있는곳에 여행을 갔다왔는데, 정말 재밌었습니다. 주변에 한세대학교라는 학교도 있고, 가면서 먹은 타코야끼도 굉장히 맛있었습니다. 산책하기 좋은 공원도 있더라구요',
    heart: 1,
    commentCount: 1,
    comments: [],
    owner: {
      _id: '123124',
      email: 'email.gmail.com',
      avatarUrl: '..',
      name: '박상훈',
      __v: unique,
    },
    createdAt: new Date(2022, 4, 15, 20, 42),
    __v: unique++,
  },
  {
    _id: String(unique),
    title: '대구 괜찮은 음식점',
    category: '음식점',
    city: '대구',
    detailCity: '북구',
    tags: '#대구#북구#꿀맛',
    contents:
      '![imageURL](https://meongmeong-tui-img-storage.s3-ap-northeast-2.amazonaws.com/db99a0ac-a6d8-44f6-9d92-4924b5e44045.jpeg)강아지 출입을 허용하는 매장이 있어서 공유해드리고자 글을 올립니다 추천해드려요!',
    heart: 1,
    commentCount: 1,
    comments: [],
    owner: {
      _id: '123124',
      email: 'email.gmail.com',
      avatarUrl: '..',
      name: '박상훈',
      __v: unique,
    },
    createdAt: new Date(2022, 4, 18, 20, 52),
    __v: unique++,
  },
  {
    _id: String(unique),
    title: '인천에있는 강아지 출입가능 숙소에 다녀왔습니다',
    category: '숙소',
    city: '인천',
    detailCity: '간석동',
    tags: '#숙소#행복#편안#꿀잼',
    contents:
      '![imageURL](https://meongmeong-tui-img-storage.s3-ap-northeast-2.amazonaws.com/4e09ada0-c708-46bc-baba-c14bfa036704.jpeg)고양이 전용 숙소가 있다는데 다들 알고 계셨나요? 인천 간석동에 위치한 곳입니다 공유해드려요!',
    heart: 1,
    commentCount: 1,
    comments: [],
    owner: {
      _id: '123124',
      email: 'email.gmail.com',
      avatarUrl: '..',
      name: '박상훈',
      __v: unique,
    },
    createdAt: new Date(2022, 4, 19, 20, 3),
    __v: unique++,
  },
  {
    _id: String(unique),
    title: '타이틀',
    category: '기타',
    city: '경기',
    detailCity: '군포',
    tags: '#산책#벤치#커피#카페',
    contents:
      '![imageURL](https://meongmeong-tui-img-storage.s3-ap-northeast-2.amazonaws.com/4c335196-d5ca-48d5-8016-647595f775df.jpeg)경기도 군포시에 산책할만한 곳이 있네요! 타코야끼도 맛있고 주변에 한세대학교 축제를 하길래 너무 재밌었습니다!',
    heart: 1,
    commentCount: 1,
    comments: [],
    owner: {
      _id: '123124',
      email: 'email.gmail.com',
      avatarUrl: '..',
      name: '박상훈',
      __v: unique,
    },
    createdAt: new Date(2022, 4, 11, 20, 3),
    __v: unique++,
  },
  {
    _id: String(unique),
    title: '여행을 다녀왔습니다',
    category: '여행',
    city: '대구',
    detailCity: '북구',
    tags: '#여행#추억#꿀잼#대구#인천',
    contents:
      '![imageURL](https://meongmeong-tui-img-storage.s3-ap-northeast-2.amazonaws.com/090d2edc-57de-4ebe-857b-82406639f22c.jpeg)너무 재밌고 기분좋았던 여행지를 추천해드리고자 게시글을 작성하게 되었습니다~',
    heart: 1,
    commentCount: 1,
    comments: [],
    owner: {
      _id: '123124',
      email: 'email.gmail.com',
      avatarUrl: '..',
      name: '박상훈',
      __v: unique,
    },
    createdAt: new Date(2022, 4, 16, 20, 42),
    __v: unique++,
  },
  {
    _id: String(unique),
    title: '타이틀',
    category: '음식점',
    city: '서울',
    detailCity: '홍대',
    tags: '#맛집#대박#서울#홍대',
    contents:
      '![imageURL](https://meongmeong-tui-img-storage.s3-ap-northeast-2.amazonaws.com/04d73daa-0d66-4228-a784-2320a703ad69.jpeg)홍대쪽에 놀러갈일이 있어서 반려동물을 데리고 갔는데 너무 맛있고, 가성비 좋은 식당이 있어서 소개해드립니다!!',
    heart: 1,
    commentCount: 1,
    comments: [],
    owner: {
      _id: '123124',
      email: 'email.gmail.com',
      avatarUrl: '..',
      name: '서은영',
      __v: unique,
    },
    createdAt: new Date(2022, 4, 20, 20, 52),
    __v: unique++,
  },
  {
    _id: String(unique),
    title: '타이틀',
    category: '숙소',
    city: '경기',
    detailCity: '군포',
    tags: '#숙소#행복#경기#군포',
    contents:
      '![imageURL](https://meongmeong-tui-img-storage.s3-ap-northeast-2.amazonaws.com/d0711b4c-25e3-44c1-bf9f-ff1d38be316b.jpeg)숙소를 알아보던 도중 반려동물을 같이 데려갈 수 있는곳이 있더라구요! 정말 잘됐습니다 저는 반려동물과 함께 행복한 시간을 보냈답니다!',
    heart: 1,
    commentCount: 1,
    comments: [],
    owner: {
      _id: '123124',
      email: 'email.gmail.com',
      avatarUrl: '..',
      name: '서은영',
      __v: unique,
    },
    createdAt: new Date(2022, 4, 20, 20, 3),
    __v: unique++,
  },
  {
    _id: String(unique),
    title: '타이틀',
    category: '기타',
    city: '서울',
    detailCity: '한강',
    tags: '#산책#공원#운동',
    contents:
      '![imageURL](https://meongmeong-tui-img-storage.s3-ap-northeast-2.amazonaws.com/8a38540c-fc7c-461c-96b7-268dc9c6d29e.jpeg)서울 한강은 역시 산책하기에 너무 좋은곳인것 같아요 다들 아실거라고 생각합니다',
    heart: 1,
    commentCount: 1,
    comments: [],
    owner: {
      _id: '123124',
      email: 'email.gmail.com',
      avatarUrl: '..',
      name: '서은영',
      __v: unique,
    },
    createdAt: new Date(2022, 4, 15, 20, 3),
    __v: unique++,
  },
  {
    _id: String(unique),
    title: '진짜 행복한 추억을 남겼네요',
    category: '여행',
    city: '부산',
    detailCity: '해운대',
    tags: '#여행#부산#바다#추억',
    contents:
      '![imageURL](https://meongmeong-tui-img-storage.s3-ap-northeast-2.amazonaws.com/6123faf9-b861-48da-8152-15cbafa67a37.jpeg)부산광역시 해운대에 놀러갔다왔어요! 강아지들이 너무 행복해했고 저도 그 모습을 보면서 너무 행복했습니다~',
    heart: 1,
    commentCount: 1,
    comments: [],
    owner: {
      _id: '123124',
      email: 'email.gmail.com',
      avatarUrl: '..',
      name: '서은영',
      __v: unique,
    },
    createdAt: new Date(2022, 4, 21, 20, 42),
    __v: unique++,
  },
  {
    _id: String(unique),
    title: '타이틀',
    category: '음식점',
    city: '인천',
    detailCity: '구월동',
    tags: '#맛집#튀김#편안',
    contents:
      '![imageURL](https://meongmeong-tui-img-storage.s3-ap-northeast-2.amazonaws.com/9c7e76ac-cc24-4593-9700-ec503dd3402c.jpeg)위치는 인천 구월동이고 튀김맛집을 갔다왔습니다! 강아지 전용 밥도 따로 판매하셔서 너무 좋았습니다!',
    heart: 1,
    commentCount: 1,
    comments: [],
    owner: {
      _id: '123124',
      email: 'email.gmail.com',
      avatarUrl: '..',
      name: '서은영',
      __v: unique,
    },
    createdAt: new Date(2022, 4, 22, 20, 52),
    __v: unique++,
  },
  {
    _id: String(unique),
    title: '타이틀',
    category: '숙소',
    city: '서울',
    detailCity: '마포동',
    tags: '#숙소#행복#편안#꿀잼',
    contents:
      '![imageURL](https://meongmeong-tui-img-storage.s3-ap-northeast-2.amazonaws.com/dcb35e89-1ffe-43c3-a5c6-a00b7d9a84f2.jpeg)강아지를 데리고 갈 수 있는 숙박시설이 있더라구요! 서울 마포동에 위치한 곳입니다. 너무 좋았어요',
    heart: 1,
    commentCount: 1,
    comments: [],
    owner: {
      _id: '123124',
      email: 'email.gmail.com',
      avatarUrl: '..',
      name: '서은영',
      __v: unique,
    },
    createdAt: new Date(2022, 4, 23, 20, 3),
    __v: unique++,
  },
  {
    _id: String(unique),
    title: '타이틀',
    category: '기타',
    city: '인천',
    detailCity: '부평',
    tags: '#산책#공부#벤치',
    contents:
      '![imageURL](https://meongmeong-tui-img-storage.s3-ap-northeast-2.amazonaws.com/8bdcd74e-1c6a-4e4c-be92-ac0e61e31c9c.jpeg)산책할만한곳이 어디있나 찾아보던 도중 인천 부평구에 괜찮은곳이 있어서 공유해드립니다',
    heart: 1,
    commentCount: 1,
    comments: [],
    owner: {
      _id: '123124',
      email: 'email.gmail.com',
      avatarUrl: '..',
      name: '서은영',
      __v: unique,
    },
    createdAt: new Date(2022, 4, 28, 2, 2),
    __v: unique++,
  },
  {
    _id: String(unique),
    title: '여행을 다녀왔습니다',
    category: '여행',
    city: '인천',
    detailCity: '부평',
    tags: '#여행#추억#꿀잼#인천',
    contents:
      '![imageURL](https://meongmeong-tui-img-storage.s3-ap-northeast-2.amazonaws.com/fb014886-a283-457e-8fdc-7f8071f92499.jpeg)너무너무 재밌는 하루였어요! 우리 이쁜 아이들좀 보세요!!!',
    heart: 1,
    commentCount: 1,
    comments: [],
    owner: {
      _id: '123124',
      email: 'email.gmail.com',
      avatarUrl: '..',
      name: '서은영',
      __v: unique,
    },
    createdAt: new Date(2022, 5, 10, 20, 42),
    __v: unique++,
  },
  {
    _id: String(unique),
    title: '경기 괜찮은 음식점',
    category: '음식점',
    city: '경기',
    detailCity: '군포',
    tags: '#경기#군포#북구#꿀맛',
    contents:
      '![imageURL](https://meongmeong-tui-img-storage.s3-ap-northeast-2.amazonaws.com/c1f863de-9507-44f0-9287-a67aa2dcefa3.jpeg)경기도 군포시에 있는 돈가스 전문점에 갔다왔는데 강아지 출입을 허용하는 매장이여서 편안하게 갔다왔습니다 추천해드려요!',
    heart: 1,
    commentCount: 1,
    comments: [],
    owner: {
      _id: '123124',
      email: 'email.gmail.com',
      avatarUrl: '..',
      name: '서은영',
      __v: unique,
    },
    createdAt: new Date(2022, 5, 8, 20, 52),
    __v: unique++,
  },
  {
    _id: String(unique),
    title: '대구에있는 강아지 출입가능 숙소에 다녀왔습니다',
    category: '숙소',
    city: '대구',
    detailCity: '북구',
    tags: '#숙소#행복#편안#꿀잼',
    contents:
      '![imageURL](https://meongmeong-tui-img-storage.s3-ap-northeast-2.amazonaws.com/37dd23e7-bf4d-4673-b726-7bb628220b82.jpeg)반려동물을 맡겨달라고 숙소에 미리 전화로 예약해두면, 전문강사님께서 맡아주시더라구요! 추가비용도 얼마안해서 부담없이 편하게 잘 다녀왔습니다. 아이들도 행복해보였어요!',
    heart: 1,
    commentCount: 1,
    comments: [],
    owner: {
      _id: '123124',
      email: 'email.gmail.com',
      avatarUrl: '..',
      name: '서은영',
      __v: unique,
    },
    createdAt: new Date(2022, 5, 4, 20, 3),
    __v: unique++,
  },
  {
    _id: String(unique),
    title: '타이틀',
    category: '기타',
    city: '부산',
    detailCity: '해운대',
    tags: '#산책#벤치#커피#카페#바다',
    contents:
      '![imageURL](https://meongmeong-tui-img-storage.s3-ap-northeast-2.amazonaws.com/cfb4b071-c273-4b05-9dbc-3cc4bf5e6ca5.jpeg)부산광역시에 공부하기 편한 벤치가 있더라구요! 주변에 카페도있고 커피마시면서 강아지 산책시키기에도 너무 좋은것 같아서 공유해드립니다!',
    heart: 1,
    commentCount: 1,
    comments: [],
    owner: {
      _id: '123124',
      email: 'email.gmail.com',
      avatarUrl: '..',
      name: '강아지최고',
      __v: unique,
    },
    createdAt: new Date(2022, 5, 2, 2, 2),
    __v: unique++,
  },
  {
    _id: String(unique),
    title: '너무 재미있는 여행이였어요',
    category: '여행',
    city: '대구',
    detailCity: '북구',
    tags: '#여행#대구#북구',
    contents:
      '![imageURL](https://meongmeong-tui-img-storage.s3-ap-northeast-2.amazonaws.com/1c208a4b-5c5e-470d-aa81-2c9a762bd66a.jpeg)대구에 여행을 갔다왔습니다. 카운터에 문의 후 반려동물을 데려갔는데 데려가서 케어해주시더라구요! 너무 좋았습니다',
    heart: 1,
    commentCount: 1,
    comments: [],
    owner: {
      _id: '123124',
      email: 'email.gmail.com',
      avatarUrl: '..',
      name: '강아지최고',
      __v: unique,
    },
    createdAt: new Date(2022, 2, 20, 2, 3),
    __v: unique++,
  },

  {
    _id: String(unique),
    title: '타이틀',
    category: '음식점',
    city: '서울',
    detailCity: '홍대',
    tags: '#맛집#대박#서울#홍대',
    contents:
      '![imageURL](https://meongmeong-tui-img-storage.s3-ap-northeast-2.amazonaws.com/f102f37f-1c79-4a75-b9be-6bf9ce46995a.jpeg)진짜 맛있는 맛집이 있는데 소개해드릴려고 합니다! 반려동물도 같이 들어갈수있대요! 너무 좋았습니다',
    heart: 1,
    commentCount: 1,
    comments: [],
    owner: {
      _id: '123124',
      email: 'email.gmail.com',
      avatarUrl: '..',
      name: '강아지최고',
      __v: unique,
    },
    createdAt: new Date(2022, 2, 20, 2, 3),
    __v: unique++,
  },
  {
    _id: String(unique),
    title: '타이틀',
    category: '숙소',
    city: '경기',
    detailCity: '군포',
    tags: '#숙소#행복#경기#군포',
    contents:
      '![imageURL](https://meongmeong-tui-img-storage.s3-ap-northeast-2.amazonaws.com/f44fd0b4-9bd2-4a62-97a3-924c24cd1075.jpeg)숙소를 알아봤는데, 반려동물도 출입이 가능한곳이 있더라구요! 정말 잘됐습니다 저는 반려동물과 함께 행복한 시간을 보냈답니다!',
    heart: 1,
    commentCount: 1,
    comments: [],
    owner: {
      _id: '123124',
      email: 'email.gmail.com',
      avatarUrl: '..',
      name: '강아지최고',
      __v: unique,
    },
    createdAt: new Date(2022, 2, 20, 2, 3),
    __v: unique++,
  },
  {
    _id: String(unique),
    title: '타이틀',
    category: '기타',
    city: '서울',
    detailCity: '마포동',
    tags: '#산책#공원#운동',
    contents:
      '![imageURL](https://meongmeong-tui-img-storage.s3-ap-northeast-2.amazonaws.com/e54a52c7-9685-46f8-b8a1-54da3ccfc1e3.jpeg)서울 마포동에 위치한 산책로인데, 다른사람들과 공유하고 싶어서 글을 올립니다 여기 되게 좋아요!',
    heart: 1,
    commentCount: 1,
    comments: [],
    owner: {
      _id: '123124',
      email: 'email.gmail.com',
      avatarUrl: '..',
      name: '강아지최고',
      __v: unique,
    },
    createdAt: new Date(2022, 2, 20, 2, 2),
    __v: unique++,
  },
  {
    _id: String(unique),
    title: '진짜 행복한 추억을 남겼네요',
    category: '여행',
    city: '부산',
    detailCity: '해운대',
    tags: '#여행#부산#바다#추억',
    contents:
      '![imageURL](https://meongmeong-tui-img-storage.s3-ap-northeast-2.amazonaws.com/e54a52c7-9685-46f8-b8a1-54da3ccfc1e3.jpeg)강아지들과 바다보러 해운대에 갔는데 강아지들이 너무 행복해했고 저도 그 모습을 보면서 너무 행복했습니다~',
    heart: 1,
    commentCount: 1,
    comments: [],
    owner: {
      _id: '123124',
      email: 'email.gmail.com',
      avatarUrl: '..',
      name: '강아지최고',
      __v: unique,
    },
    createdAt: new Date(2022, 3, 23, 18, 22),
    __v: unique++,
  },
  {
    _id: String(unique),
    title: '타이틀',
    category: '음식점',
    city: '인천',
    detailCity: '구월동',
    tags: '#맛집#튀김#편안',
    contents:
      '![imageURL](https://meongmeong-tui-img-storage.s3-ap-northeast-2.amazonaws.com/f44fd0b4-9bd2-4a62-97a3-924c24cd1075.jpeg)인천 구월동에 있는 튀김 전문점에 갔다왔는데 강아지 출입을 허용하는 매장이여서 편안하게 갔다왔습니다 추천해드려요!',
    heart: 1,
    commentCount: 1,
    comments: [],
    owner: {
      _id: '123124',
      email: 'email.gmail.com',
      avatarUrl: '..',
      name: '강아지최고',
      __v: unique,
    },
    createdAt: new Date(2022, 3, 23, 18, 22),
    __v: unique++,
  },
  {
    _id: String(unique),
    title: '타이틀',
    category: '숙소',
    city: '서울',
    detailCity: '마포동',
    tags: '#숙소#행복#편안#꿀잼',
    contents:
      '![imageURL](https://meongmeong-tui-img-storage.s3-ap-northeast-2.amazonaws.com/f102f37f-1c79-4a75-b9be-6bf9ce46995a.jpeg)전문강사님께서 반려동물을 맡아주시는 숙소가 있습니다! 추가비용도 얼마안해서 부담없이 편하게 잘 다녀왔습니다. 아이들도 행복해보였어요!',
    heart: 1,
    commentCount: 1,
    comments: [],
    owner: {
      _id: '123124',
      email: 'email.gmail.com',
      avatarUrl: '..',
      name: '고양이최고',
      __v: unique,
    },
    createdAt: new Date(2022, 3, 23, 18, 22),
    __v: unique++,
  },
  {
    _id: String(unique),
    title: '타이틀',
    category: '기타',
    city: '인천',
    detailCity: '부평',
    tags: '#산책#공부#벤치',
    contents:
      '![imageURL](https://meongmeong-tui-img-storage.s3-ap-northeast-2.amazonaws.com/1c208a4b-5c5e-470d-aa81-2c9a762bd66a.jpeg)너무 좋은곳을 발견했는데, 저 혼자 알기 아쉬워서 공유하고자 글을 올리게 되었습니다. 강아지들이 너무 좋아하는 산책로에요! 인천 부평구입니다',
    heart: 1,
    commentCount: 1,
    comments: [],
    owner: {
      _id: '123124',
      email: 'email.gmail.com',
      avatarUrl: '..',
      name: '고양이최고',
      __v: unique,
    },
    createdAt: new Date(2022, 3, 23, 18, 22),
    __v: unique++,
  },
  {
    _id: String(unique),
    title: '너무 재미있는 여행이였어요',
    category: '여행',
    city: '경기',
    detailCity: '군포',
    tags: '#여행#경기#군포',
    contents:
      '![imageURL](https://meongmeong-tui-img-storage.s3-ap-northeast-2.amazonaws.com/cfb4b071-c273-4b05-9dbc-3cc4bf5e6ca5.jpeg)경기도 군포시에 있는곳에 여행을 갔다왔는데, 정말 재밌었습니다. 주변에 한세대학교라는 학교도 있고, 가면서 먹은 타코야끼도 굉장히 맛있었습니다. 산책하기 좋은 공원도 있더라구요',
    heart: 1,
    commentCount: 1,
    comments: [],
    owner: {
      _id: '123124',
      email: 'email.gmail.com',
      avatarUrl: '..',
      name: '루이주인',
      __v: unique,
    },
    createdAt: new Date(2022, 4, 15, 20, 42),
    __v: unique++,
  },
  {
    _id: String(unique),
    title: '대구 괜찮은 음식점',
    category: '음식점',
    city: '대구',
    detailCity: '북구',
    tags: '#대구#북구#꿀맛',
    contents:
      '![imageURL](https://meongmeong-tui-img-storage.s3-ap-northeast-2.amazonaws.com/37dd23e7-bf4d-4673-b726-7bb628220b82.jpeg)강아지 출입을 허용하는 매장이 있어서 공유해드리고자 글을 올립니다 추천해드려요!',
    heart: 1,
    commentCount: 1,
    comments: [],
    owner: {
      _id: '123124',
      email: 'email.gmail.com',
      avatarUrl: '..',
      name: '예삐주인',
      __v: unique,
    },
    createdAt: new Date(2022, 4, 18, 20, 52),
    __v: unique++,
  },
  {
    _id: String(unique),
    title: '인천에있는 강아지 출입가능 숙소에 다녀왔습니다',
    category: '숙소',
    city: '인천',
    detailCity: '간석동',
    tags: '#숙소#행복#편안#꿀잼',
    contents:
      '![imageURL](https://meongmeong-tui-img-storage.s3-ap-northeast-2.amazonaws.com/c1f863de-9507-44f0-9287-a67aa2dcefa3.jpeg)고양이 전용 숙소가 있다는데 다들 알고 계셨나요? 인천 간석동에 위치한 곳입니다 공유해드려요!',
    heart: 1,
    commentCount: 1,
    comments: [],
    owner: {
      _id: '123124',
      email: 'email.gmail.com',
      avatarUrl: '..',
      name: '인천사는집사',
      __v: unique,
    },
    createdAt: new Date(2022, 4, 19, 20, 3),
    __v: unique++,
  },
  {
    _id: String(unique),
    title: '타이틀',
    category: '기타',
    city: '경기',
    detailCity: '군포',
    tags: '#산책#벤치#커피#카페',
    contents:
      '![imageURL](https://meongmeong-tui-img-storage.s3-ap-northeast-2.amazonaws.com/fb014886-a283-457e-8fdc-7f8071f92499.jpeg)경기도 군포시에 산책할만한 곳이 있네요! 타코야끼도 맛있고 주변에 한세대학교 축제를 하길래 너무 재밌었습니다!',
    heart: 1,
    commentCount: 1,
    comments: [],
    owner: {
      _id: '123124',
      email: 'email.gmail.com',
      avatarUrl: '..',
      name: '집사는힘들어',
      __v: unique,
    },
    createdAt: new Date(2022, 4, 11, 20, 3),
    __v: unique++,
  },
  {
    _id: String(unique),
    title: '여행을 다녀왔습니다',
    category: '여행',
    city: '대구',
    detailCity: '북구',
    tags: '#여행#추억#꿀잼#대구',
    contents:
      '![imageURL](https://meongmeong-tui-img-storage.s3-ap-northeast-2.amazonaws.com/8bdcd74e-1c6a-4e4c-be92-ac0e61e31c9c.jpeg)너무 재밌고 기분좋았던 여행지를 추천해드리고자 게시글을 작성하게 되었습니다~',
    heart: 1,
    commentCount: 1,
    comments: [],
    owner: {
      _id: '123124',
      email: 'email.gmail.com',
      avatarUrl: '..',
      name: '우와아아아',
      __v: unique,
    },
    createdAt: new Date(2022, 4, 16, 20, 42),
    __v: unique++,
  },
  {
    _id: String(unique),
    title: '타이틀',
    category: '음식점',
    city: '서울',
    detailCity: '홍대',
    tags: '#맛집#대박#서울#홍대',
    contents:
      '![imageURL](https://meongmeong-tui-img-storage.s3-ap-northeast-2.amazonaws.com/dcb35e89-1ffe-43c3-a5c6-a00b7d9a84f2.jpeg)홍대쪽에 놀러갈일이 있어서 반려동물을 데리고 갔는데 너무 맛있고, 가성비 좋은 식당이 있어서 소개해드립니다!!',
    heart: 1,
    commentCount: 1,
    comments: [],
    owner: {
      _id: '123124',
      email: 'email.gmail.com',
      avatarUrl: '..',
      name: '맥북쓰는집사',
      __v: unique,
    },
    createdAt: new Date(2022, 4, 20, 20, 52),
    __v: unique++,
  },
  {
    _id: String(unique),
    title: '타이틀',
    category: '숙소',
    city: '경기',
    detailCity: '군포',
    tags: '#숙소#행복#경기#군포',
    contents:
      '![imageURL](https://meongmeong-tui-img-storage.s3-ap-northeast-2.amazonaws.com/9c7e76ac-cc24-4593-9700-ec503dd3402c.jpeg)숙소를 알아보던 도중 반려동물을 같이 데려갈 수 있는곳이 있더라구요! 정말 잘됐습니다 저는 반려동물과 함께 행복한 시간을 보냈답니다!',
    heart: 1,
    commentCount: 1,
    comments: [],
    owner: {
      _id: '123124',
      email: 'email.gmail.com',
      avatarUrl: '..',
      name: '개발하는집사',
      __v: unique,
    },
    createdAt: new Date(2022, 4, 20, 20, 3),
    __v: unique++,
  },
  {
    _id: String(unique),
    title: '타이틀',
    category: '기타',
    city: '서울',
    detailCity: '한강',
    tags: '#산책#공원#운동',
    contents:
      '![imageURL](https://meongmeong-tui-img-storage.s3-ap-northeast-2.amazonaws.com/6123faf9-b861-48da-8152-15cbafa67a37.jpeg)서울 한강은 역시 산책하기에 너무 좋은곳인것 같아요 다들 아실거라고 생각합니다',
    heart: 1,
    commentCount: 1,
    comments: [],
    owner: {
      _id: '123124',
      email: 'email.gmail.com',
      avatarUrl: '..',
      name: '한강산책최고',
      __v: unique,
    },
    createdAt: new Date(2022, 4, 15, 20, 3),
    __v: unique++,
  },
  {
    _id: String(unique),
    title: '진짜 행복한 추억을 남겼네요',
    category: '여행',
    city: '부산',
    detailCity: '해운대',
    tags: '#여행#부산#바다#추억',
    contents:
      '![imageURL](https://meongmeong-tui-img-storage.s3-ap-northeast-2.amazonaws.com/8a38540c-fc7c-461c-96b7-268dc9c6d29e.jpeg)부산광역시 해운대에 놀러갔다왔어요! 강아지들이 너무 행복해했고 저도 그 모습을 보면서 너무 행복했습니다~',
    heart: 1,
    commentCount: 1,
    comments: [],
    owner: {
      _id: '123124',
      email: 'email.gmail.com',
      avatarUrl: '..',
      name: '부산사는학생',
      __v: unique,
    },
    createdAt: new Date(2022, 4, 21, 20, 42),
    __v: unique++,
  },
  {
    _id: String(unique),
    title: '타이틀',
    category: '음식점',
    city: '인천',
    detailCity: '구월동',
    tags: '#맛집#튀김#편안',
    contents:
      '![imageURL](https://meongmeong-tui-img-storage.s3-ap-northeast-2.amazonaws.com/d0711b4c-25e3-44c1-bf9f-ff1d38be316b.jpeg)위치는 인천 구월동이고 튀김맛집을 갔다왔습니다! 강아지 전용 밥도 따로 판매하셔서 너무 좋았습니다!',
    heart: 1,
    commentCount: 1,
    comments: [],
    owner: {
      _id: '123124',
      email: 'email.gmail.com',
      avatarUrl: '..',
      name: '고양이최고',
      __v: unique,
    },
    createdAt: new Date(2022, 4, 22, 20, 52),
    __v: unique++,
  },
  {
    _id: String(unique),
    title: '타이틀',
    category: '숙소',
    city: '서울',
    detailCity: '마포동',
    tags: '#숙소#행복#편안#꿀잼',
    contents:
      '![imageURL](https://meongmeong-tui-img-storage.s3-ap-northeast-2.amazonaws.com/04d73daa-0d66-4228-a784-2320a703ad69.jpeg)강아지를 데리고 갈 수 있는 숙박시설이 있더라구요! 서울 마포동에 위치한 곳입니다. 너무 좋았어요',
    heart: 1,
    commentCount: 1,
    comments: [],
    owner: {
      _id: '123124',
      email: 'email.gmail.com',
      avatarUrl: '..',
      name: '강아지최고',
      __v: unique,
    },
    createdAt: new Date(2022, 4, 23, 20, 3),
    __v: unique++,
  },
  {
    _id: String(unique),
    title: '타이틀',
    category: '기타',
    city: '인천',
    detailCity: '부평',
    tags: '#산책#공부#벤치',
    contents:
      '![imageURL](https://meongmeong-tui-img-storage.s3-ap-northeast-2.amazonaws.com/090d2edc-57de-4ebe-857b-82406639f22c.jpeg)산책할만한곳이 어디있나 찾아보던 도중 인천 부평구에 괜찮은곳이 있어서 공유해드립니다',
    heart: 1,
    commentCount: 1,
    comments: [],
    owner: {
      _id: '123124',
      email: 'email.gmail.com',
      avatarUrl: '..',
      name: '반려동물최고',
      __v: unique,
    },
    createdAt: new Date(2022, 4, 28, 2, 2),
    __v: unique++,
  },
  {
    _id: String(unique),
    title: '여행을 다녀왔습니다',
    category: '여행',
    city: '인천',
    detailCity: '부평',
    tags: '#여행#추억#꿀잼#인천',
    contents:
      '![imageURL](https://meongmeong-tui-img-storage.s3-ap-northeast-2.amazonaws.com/4c335196-d5ca-48d5-8016-647595f775df.jpeg)너무너무 재밌는 하루였어요! 우리 이쁜 아이들좀 보세요!!!',
    heart: 1,
    commentCount: 1,
    comments: [],
    owner: {
      _id: '123124',
      email: 'email.gmail.com',
      avatarUrl: '..',
      name: '지나가는학생',
      __v: unique,
    },
    createdAt: new Date(2022, 5, 10, 20, 42),
    __v: unique++,
  },
  {
    _id: String(unique),
    title: '경기 괜찮은 음식점',
    category: '음식점',
    city: '경기',
    detailCity: '군포',
    tags: '#경기#군포#북구#꿀맛',
    contents:
      '![imageURL](https://meongmeong-tui-img-storage.s3-ap-northeast-2.amazonaws.com/4e09ada0-c708-46bc-baba-c14bfa036704.jpeg)경기도 군포시에 있는 돈가스 전문점에 갔다왔는데 강아지 출입을 허용하는 매장이여서 편안하게 갔다왔습니다 추천해드려요!',
    heart: 1,
    commentCount: 1,
    comments: [],
    owner: {
      _id: '123124',
      email: 'email.gmail.com',
      avatarUrl: '..',
      name: '주인또는집사',
      __v: unique,
    },
    createdAt: new Date(2022, 5, 8, 20, 52),
    __v: unique++,
  },
  {
    _id: String(unique),
    title: '대구에있는 강아지 출입가능 숙소에 다녀왔습니다',
    category: '숙소',
    city: '대구',
    detailCity: '북구',
    tags: '#숙소#행복#편안#꿀잼',
    contents:
      '![imageURL](https://meongmeong-tui-img-storage.s3-ap-northeast-2.amazonaws.com/db99a0ac-a6d8-44f6-9d92-4924b5e44045.jpeg)반려동물을 맡겨달라고 숙소에 미리 전화로 예약해두면, 전문강사님께서 맡아주시더라구요! 추가비용도 얼마안해서 부담없이 편하게 잘 다녀왔습니다. 아이들도 행복해보였어요!',
    heart: 1,
    commentCount: 1,
    comments: [],
    owner: {
      _id: '123124',
      email: 'email.gmail.com',
      avatarUrl: '..',
      name: '고양이주인',
      __v: unique,
    },
    createdAt: new Date(2022, 5, 4, 20, 3),
    __v: unique++,
  },
  {
    _id: String(unique),
    title: '타이틀',
    category: '기타',
    city: '부산',
    detailCity: '해운대',
    tags: '#산책#벤치#커피#카페#바다',
    contents:
      '![imageURL](https://meongmeong-tui-img-storage.s3-ap-northeast-2.amazonaws.com/2278d5b9-2965-47a6-9cac-36a8f82fcd59.jpeg)부산광역시에 공부하기 편한 벤치가 있더라구요! 주변에 카페도있고 커피마시면서 강아지 산책시키기에도 너무 좋은것 같아서 공유해드립니다!',
    heart: 1,
    commentCount: 1,
    comments: [],
    owner: {
      _id: '123124',
      email: 'email.gmail.com',
      avatarUrl: '..',
      name: '강아지주인',
      __v: unique,
    },
    createdAt: new Date(2022, 5, 2, 2, 2),
    __v: unique++,
  },
];

export const InformationBoard = InformationBoardData.reverse();