import { InformationBoardType } from 'src/types/board.type';
export const InformationBoard: InformationBoardType[] = [
  {
    _id: '1',
    title: '타이틀',
    category: '음식점',
    city: '인천',
    detailCity: '구월동',
    tags: '#태그#나중에#분리하기',
    contents: '여기에 내용, 사진 같이 들어감',
    heart: 1,
    commentCount: 1,
    comments: [],
    owner: {
      _id: '123124',
      email: 'email.gmail.com',
      avatarUrl: '..',
      name: '게시글작성자',
      __v: 1,
    },
    createdAt: new Date(),
    __v: 1,
  },
  {
    _id: '2',
    title: '타이틀',
    category: '음식점',
    city: '인천',
    detailCity: '구월동',
    tags: '#태그#나중에#분리하기',
    contents: '여기에 내용, 사진 같이 들어감',
    heart: 1,
    commentCount: 1,
    comments: [],
    owner: {
      _id: '123124',
      email: 'email.gmail.com',
      avatarUrl: '..',
      name: '게시글작성자',
      __v: 2,
    },
    createdAt: new Date(),
    __v: 2,
  },
  {
    _id: '3',
    title: '타이틀',
    category: '음식점',
    city: '인천',
    detailCity: '구월동',
    tags: '#태그#나중에#분리하기',
    contents: '여기에 내용, 사진 같이 들어감',
    heart: 1,
    commentCount: 1,
    comments: [],
    owner: {
      _id: '123124',
      email: 'email.gmail.com',
      avatarUrl: '..',
      name: '게시글작성자',
      __v: 3,
    },
    createdAt: new Date(),
    __v: 3,
  },
  {
    _id: '4',
    title: '타이틀',
    category: '음식점',
    city: '인천',
    detailCity: '구월동',
    tags: '#태그#나중에#분리하기',
    contents: '여기에 내용, 사진 같이 들어감',
    heart: 1,
    commentCount: 1,
    comments: [],
    owner: {
      _id: '123124',
      email: 'email.gmail.com',
      avatarUrl: '..',
      name: '게시글작성자',
      __v: 4,
    },
    createdAt: new Date(),
    __v: 4,
  },
  {
    _id: '5',
    title: '타이틀',
    category: '음식점',
    city: '인천',
    detailCity: '구월동',
    tags: '#태그#나중에#분리하기',
    contents: '여기에 내용, 사진 같이 들어감',
    heart: 1,
    commentCount: 1,
    comments: [],
    owner: {
      _id: '123124',
      email: 'email.gmail.com',
      avatarUrl: '..',
      name: '게시글작성자',
      __v: 5,
    },
    createdAt: new Date(),
    __v: 5,
  },
  {
    _id: '6',
    title: '타이틀',
    category: '음식점',
    city: '인천',
    detailCity: '구월동',
    tags: '#태그#나중에#분리하기',
    contents: '여기에 내용, 사진 같이 들어감',
    heart: 1,
    commentCount: 1,
    comments: [],
    owner: {
      _id: '123124',
      email: 'email.gmail.com',
      avatarUrl: '..',
      name: '게시글작성자',
      __v: 6,
    },
    createdAt: new Date(),
    __v: 6,
  },
  {
    _id: '7',
    title: '타이틀',
    category: '음식점',
    city: '인천',
    detailCity: '구월동',
    tags: '#태그#나중에#분리하기',
    contents: '여기에 내용, 사진 같이 들어감',
    heart: 1,
    commentCount: 1,
    comments: [],
    owner: {
      _id: '123124',
      email: 'email.gmail.com',
      avatarUrl: '..',
      name: '게시글작성자',
      __v: 7,
    },
    createdAt: new Date(),
    __v: 7,
  },
  {
    _id: '8',
    title: '타이틀',
    category: '음식점',
    city: '인천',
    detailCity: '구월동',
    tags: '#태그#나중에#분리하기',
    contents: '여기에 내용, 사진 같이 들어감',
    heart: 1,
    commentCount: 1,
    comments: [],
    owner: {
      _id: '123124',
      email: 'email.gmail.com',
      avatarUrl: '..',
      name: '게시글작성자',
      __v: 8,
    },
    createdAt: new Date(),
    __v: 8,
  },
  {
    _id: '9',
    title: '타이틀',
    category: '음식점',
    city: '인천',
    detailCity: '구월동',
    tags: '#태그#나중에#분리하기',
    contents: '여기에 내용, 사진 같이 들어감',
    heart: 1,
    commentCount: 1,
    comments: [],
    owner: {
      _id: '123124',
      email: 'email.gmail.com',
      avatarUrl: '..',
      name: '게시글작성자',
      __v: 9,
    },
    createdAt: new Date(),
    __v: 9,
  },
  {
    _id: '10',
    title: '타이틀',
    category: '음식점',
    city: '인천',
    detailCity: '구월동',
    tags: '#태그#나중에#분리하기',
    contents: '여기에 내용, 사진 같이 들어감',
    heart: 1,
    commentCount: 1,
    comments: [],
    owner: {
      _id: '123124',
      email: 'email.gmail.com',
      avatarUrl: '..',
      name: '게시글작성자',
      __v: 10,
    },
    createdAt: new Date(),
    __v: 10,
  },
  {
    _id: '11',
    title: '타이틀',
    category: '음식점',
    city: '인천',
    detailCity: '구월동',
    tags: '#태그#나중에#분리하기',
    contents: '여기에 내용, 사진 같이 들어감',
    heart: 1,
    commentCount: 1,
    comments: [],
    owner: {
      _id: '123124',
      email: 'email.gmail.com',
      avatarUrl: '..',
      name: '게시글작성자',
      __v: 11,
    },
    createdAt: new Date(),
    __v: 11,
  },
  {
    _id: '12',
    title: '타이틀',
    category: '음식점',
    city: '인천',
    detailCity: '구월동',
    tags: '#태그#나중에#분리하기',
    contents: '여기에 내용, 사진 같이 들어감',
    heart: 1,
    commentCount: 1,
    comments: [],
    owner: {
      _id: '123124',
      email: 'email.gmail.com',
      avatarUrl: '..',
      name: '게시글작성자',
      __v: 12,
    },
    createdAt: new Date(),
    __v: 12,
  },
];
